export const frenchLessons = [
  {
    level: 'A1',
    lessons: [
      {
        id: 'fr-a1-1',
        order: 1,
        icon: '\u{1F44B}',
        xp: 50,
        duration: 8,
        title: {
          native: 'Se présenter',
          darija: 'كيفاش تعرف على راسك',
          ar: 'التعريف بالنفس',
          fr: 'Se présenter',
          en: 'Introducing yourself',
        },
        subtitle: {
          darija: 'الاسم، العمر، والبلد فـ الفرنسية',
          ar: 'الاسم والعمر والبلد',
          fr: 'Nom, âge et pays',
          en: 'Name, age and country',
        },
        intro: {
          darija: 'الفرنسية فيها أداة التعريف: **le** (مذكر)، **la** (مؤنث)، **les** (جمع). هاد الدرس غادي يعلمك كيفاش تستعملها فـ التعارف.',
          ar: 'الفرنسية فيها أدوات التعريف: le للذكر، la للمؤنث، les للجمع.',
          fr: 'En français, on utilise les articles : le (masculin), la (féminin), les (pluriel).',
        },
        sections: [
          {
            type: 'text',
            body: {
              fr: "**Bonjour**, je m'appelle Youssef. J'ai vingt-cinq ans. Je viens du Maroc, mais je vis à Paris.\n\nPour demander le prénom : **Comment tu t'appelles ?** ( familier ) ou **Comment vous appelez-vous ?** ( poli ).",
              darija: '**Bonjour** = السلام عليكم. **Je m\'appelle** = سمّيتي. **J\'ai** = عندي (العمر). **Je viens du Maroc** = جيت من المغرب. **Je vis à Paris** = ساكن فـ باريس.\n\nباش تسول شي حد على سميتو: **Comment tu t’appelles ?** (عادي) ولا **Comment vous appelez-vous ?** (بالأدب).',
              ar: 'لكي تسأل أحداً عن اسمه: Comment tu t’appelles ؟ أو vous appelez-vous ؟',
            },
          },
          {
            type: 'text',
            body: {
              fr: "**Attention à l’accord !** Le nom prend le genre de la personne :\n\n* Youssef → **le** student (étudiant)\n* Fatima → **la** étudiante\n\nLe verbe **être** change aussi : je **suis**, tu **es**, il/elle **est**, nous **sommes**, vous **êtes**, ils/elles **sont**.",
              darija: '**انتبه للمطابقة!** الاسم كياخد الجنس ديال الشخص: محمد = ذكر، فاطمة = مؤنث.\n\nوالفعل **être** كيتبدل: je **suis** (أنا)، tu **es**، il/elle **est**، nous **sommes**، vous **êtes**، ils/elles **sont**.',
              ar: 'انتبه لتطابق الجنس مع الاسم، وتصريف الفعل être يتغير حسب الضمير.',
            },
          },
        ],
        examples: [
          {
            source: "Bonjour, je m'appelle Amine. Et toi ?",
            translation: { darija: 'السلام عليكم، سميتي أمين. و نتا؟', ar: 'مرحبًا، اسمي أمين. وأنت؟', fr: 'Bonjour, je m’appelle Amine. Et toi ?', en: 'Hi, I am Amine. And you?' },
            audio: 'fr-FR',
          },
          {
            source: "Je viens de Casablanca, je vis à Lyon.",
            translation: { darija: 'جيت من الدار البيضاء، ساكن فـ ليون.', ar: 'أنا من الدار البيضاء، أعيش في ليون.', fr: 'Je viens de Casablanca, je vis à Lyon.', en: 'I am from Casablanca, I live in Lyon.' },
            audio: 'fr-FR',
          },
          {
            source: "Vous appelez-vous Madame Alaoui ?",
            translation: { darija: 'واش سميتك مدام العلوي؟', ar: 'هل اسمك مدام العلوي؟', fr: 'Vous appelez-vous Madame Alaoui ?', en: 'Are you Mrs Alaoui?' },
            audio: 'fr-FR',
          },
        ],
        vocab: [
          { word: "je m'appelle", translit: 'zhuh ma-pel', audio: 'fr-FR', translation: { darija: 'سمّيتي', ar: 'اسمي', fr: 'je m’appelle', en: 'my name is' } },
          { word: 'Comment tu t’appelles ?', audio: 'fr-FR', translation: { darija: 'واش سميتك؟', ar: 'ما اسمك؟', fr: 'quel est ton prénom ?', en: 'what is your name?' } },
          { word: 'Bonjour', audio: 'fr-FR', translation: { darija: 'صباح الخير / مساء الخير', ar: 'مرحبًا', fr: 'bonjour', en: 'hello' } },
          { word: "Bonsoir", audio: 'fr-FR', translation: { darija: 'مساء الخير', ar: 'مساء الخير', fr: 'bonsoir', en: 'good evening' } },
          { word: "j'ai ... ans", audio: 'fr-FR', translation: { darija: 'عندي ... عام', ar: 'عمري ... سنة', fr: 'j’ai ... ans', en: 'I am ... years old' } },
          { word: 'je viens du Maroc', audio: 'fr-FR', translation: { darija: 'جيت من المغرب', ar: 'أنا من المغرب', fr: 'je viens du Maroc', en: 'I come from Morocco' } },
          { word: 'je vis à', audio: 'fr-FR', translation: { darija: 'ساكن فـ', ar: 'أعيش في', fr: 'je vis à', en: 'I live in' } },
          { word: 'enchanté(e)', audio: 'fr-FR', translation: { darija: 'تشرفنا', ar: 'تشرفت', fr: 'enchanté(e)', en: 'nice to meet you' } },
          { word: 'merci', audio: 'fr-FR', translation: { darija: 'شكراً', ar: 'شكرًا', fr: 'merci', en: 'thank you' } },
        ],
        exercises: [
          {
            id: 'fr-a1-1-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'Comment ____ ?', fr: 'Comment ____ ?', en: 'What is your name?' },
            options: [
              { text: 'tu t’appelles' },
              { text: 'tu es' },
              { text: 'tu viens' },
              { text: 'tu as' },
            ],
            answer: 0,
            explanation: { darija: 'الطريقة الصحيحة: Comment tu t’appelles ؟', fr: 'La bonne formule : « Comment tu t’appelles ? »', en: 'The correct phrase is "Comment tu t’appelles ?".' },
          },
          {
            id: 'fr-a1-1-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'Je ______ , je m’appelle Sara.', fr: 'Complète : Je ______ , je m’appelle Sara.', en: 'Complete: I am ______ called Sara.' },
            answer: 'm’appelle',
            accept: ['m’appelle', 'appelle', 'm\'appelle', 'mappelle'],
            explanation: { darija: 'فـ الفرنسية: je m’appelle, tu t’appelles, il s’appelle.', fr: 'En français : je m’appelle, tu t’appelles, il s’appelle.', en: 'In French: je m’appelle, tu t’appelles, il s’appelle.' },
          },
          {
            id: 'fr-a1-1-e3',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'Elle ___ étudiante.', fr: 'Elle ___ étudiante.', en: 'She is a student.' },
            options: [
              { text: 'suis' },
              { text: 'es' },
              { text: 'est' },
              { text: 'sommes' },
            ],
            answer: 2,
            explanation: { darija: 'elle est = هي كيكون / تكون.', fr: '« elle est » = elle est.', en: '"elle est" means "she is".' },
          },
          {
            id: 'fr-a1-1-e4',
            type: 'translate',
            xp: 10,
            prompt: { fr: 'I come from Morocco.', en: 'I come from Morocco.', darija: 'جيت من المغرب' },
            answer: 'je viens du Maroc',
            accept: ['je viens du Maroc', 'Je viens du Maroc', 'je viens du maroc', 'jviens du maroc'],
            explanation: { darija: '« je viens de » = جيت من (بلا كلمة من).', fr: '« je viens de » = je viens de.', en: '"je viens de" = I come from.' },
          },
          {
            id: 'fr-a1-1-e5',
            type: 'listen',
            xp: 15,
            audio: 'fr-FR',
            audioText: "Je m'appelle Fatima et j'ai trente ans.",
            prompt: { fr: 'Écoute. Quel âge a-t-elle ?', en: 'Listen. How old is she?' },
            options: [
              { text: '13 ans' },
              { text: '30 ans' },
              { text: '40 ans' },
              { text: '50 ans' },
            ],
            answer: 1,
            explanation: { darija: 'trente = 30.', fr: 'trente = 30.', en: 'trente means 30.' },
          },
          {
            id: 'fr-a1-1-e6',
            type: 'speak',
            xp: 20,
            audio: 'fr-FR',
            audioText: "Bonjour, je m'appelle Youssef et j'ai vingt-cinq ans.",
            prompt: { fr: 'Dis : « Bonjour, je m’appelle Youssef et j’ai vingt-cinq ans. »', en: 'Say: "Hello, my name is Youssef and I am 25."' },
            explanation: { darija: 'ركّز على النطق ديال «r» الفرنسية.', fr: 'Attention au « r » français.', en: 'Focus on the French "r" sound.' },
          },
          {
            id: 'fr-a1-1-e7',
            type: 'order',
            xp: 15,
            prompt: { darija: 'رتّب الكلمات باش تصاوب جملة مزيان.', fr: 'Remets les mots dans l’ordre pour faire une phrase correcte.', en: 'Put the words in order to build a correct sentence.' },
            audio: 'fr-FR',
            audioText: "Je suis du Maroc.",
            tokens: ['Maroc', 'du', 'je', 'suis'],
            answer: ['je', 'suis', 'du', 'Maroc'],
            explanation: { darija: 'الترتيب الصحيح هو: Je suis du Maroc.', fr: 'L’ordre correct est : Je suis du Maroc.', en: 'The correct order is: Je suis du Maroc.' },
          },
        ],
      },
      {
        id: 'fr-a1-2',
        order: 2,
        icon: '\u{1F6CD}',
        xp: 50,
        duration: 9,
        title: {
          native: 'À la maison',
          darija: 'فـ الدار',
          ar: 'في البيت',
          fr: 'À la maison',
          en: 'At home',
        },
        subtitle: {
          darija: 'الأثاث، الأفعال، و les prépositions',
          ar: 'الأثاث والحروف الجرية',
          fr: 'Meubles et prépositions',
          en: 'Furniture and prepositions',
        },
        intro: {
          darija: 'فـ الفرنسية كاينين حروف جرّ (prépositions) لزمان والمكان: **à**، **dans**، **sur**، **sous**، **avec**. خاصك تحفظهم مع المراد.',
          ar: 'في الفرنسية حروف جر للأماكن: à, dans, sur, sous, avec.',
          fr: 'Les prépositions en français : à, dans, sur, sous, avec. Apprenez-les avec leur sens.',
        },
        sections: [
          {
            type: 'text',
            body: {
              fr: "**dans** = داخل شي ح 공간 ماشي مفتوح (maison, voiture, ville) → *dans la maison*\n**sur** = فوق شي سطح → *sur la table*\n**à** = فـ بلاصة عامة ولا عند → *à la maison*, *à Casablanca*\n**sous** = تحت → *sous le lit*\n**avec** = مع → *avec mon frère*",
              darija: '**dans** = داخل (دار، طوموبيل، مدينة). **sur** = فوق (طابلة). **à** = فـ بلاصة عامة. **sous** = تحت. **avec** = مع.\n\nالحرف ديال النسب كيتبدل حسب الكلمة اللي بعدها: **de** (د) قبل الصوت، **du** قبل الصوت، **des** مع الجمع، **de le** → **du**، **de les** → **des**.',
              ar: 'انتبه لشكل الحرف: de تصبح du قبل الكلمة، و de le تصبح du، و de les تصبح des.',
            },
          },
          {
            type: 'text',
            body: {
              fr: "**avoir** (to have) : j’ai, tu as, il/elle a, nous avons, vous avez, ils/elles ont.\n\nExemple : *J’ai un appartement à Lyon.* = I have a flat in Lyon.",
              darija: 'فعل **avoir** (عندك): j’ai (عندي)، tu as، il a، nous avons، vous avez، ils ont.\n\nمثال: **J’ai un appartement à Lyon** = عندي شقة فـ ليون.',
              ar: 'فعل avoir يتغير حسب الضمير: j’ai, tu as, il a, nous avons…',
            },
          },
        ],
        examples: [
          {
            source: "J’ai un appartement à Casablanca.",
            translation: { darija: 'عندي شقة فـ الدار البيضاء.', ar: 'لدي شقة في الدار البيضاء.', fr: 'J’ai un appartement à Casablanca.', en: 'I have a flat in Casablanca.' },
            audio: 'fr-FR',
          },
          {
            source: "Le livre est sur la table.",
            translation: { darija: 'الكتاب فوق الطابلة.', ar: 'الكتاب على الطاولة.', fr: 'Le livre est sur la table.', en: 'The book is on the table.' },
            audio: 'fr-FR',
          },
          {
            source: "Je vais chez ma sœur avec mes parents.",
            translation: { darija: 'غادي نمشي عند أختي مع الوالدين.', ar: 'سأذهب إلى أختبي مع والديّ.', fr: 'Je vais chez ma sœur avec mes parents.', en: 'I am going to my sister’s with my parents.' },
            audio: 'fr-FR',
          },
        ],
        vocab: [
          { word: 'la maison', audio: 'fr-FR', translation: { darija: 'البيت', ar: 'المنزل', fr: 'la maison', en: 'the house' } },
          { word: 'la chambre', audio: 'fr-FR', translation: { darija: 'الغرفة', ar: 'الغرفة', fr: 'la chambre', en: 'the bedroom' } },
          { word: 'la cuisine', audio: 'fr-FR', translation: { darija: 'المطبخ', ar: 'المطبخ', fr: 'la cuisine', en: 'the kitchen' } },
          { word: 'la table', audio: 'fr-FR', translation: { darija: 'الطابلة', ar: 'الطاولة', fr: 'la table', en: 'the table' } },
          { word: 'le lit', audio: 'fr-FR', translation: { darija: 'الفراش', ar: 'السرير', fr: 'le lit', en: 'the bed' } },
          { word: "l'appartement", audio: 'fr-FR', translation: { darija: 'الشقة', ar: 'الشقة', fr: 'l’appartement', en: 'the flat' } },
          { word: 'avec', audio: 'fr-FR', translation: { darija: 'مع', ar: 'مع', fr: 'avec', en: 'with' } },
          { word: 'sans', audio: 'fr-FR', translation: { darija: 'بلا', ar: 'بدون', fr: 'sans', en: 'without' } },
          { word: 'chez', audio: 'fr-FR', translation: { darija: 'عند', ar: 'عند', fr: 'chez', en: 'at someone’s' } },
        ],
        exercises: [
          {
            id: 'fr-a1-2-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'J’ai ___ appartement à Rabat.', fr: 'J’ai ___ appartement à Rabat.', en: 'I have a flat in Rabat.' },
            options: [
              { text: 'le' },
              { text: 'la' },
              { text: 'un' },
              { text: 'des' },
            ],
            answer: 2,
            explanation: { darija: '«un appartement» مؤنث، ولكن «un» صحيح هنا.', fr: '« un appartement » est masculin.', en: '"un appartement" is masculine, so "un".' },
          },
          {
            id: 'fr-a1-2-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'Le chat est ___ la table.', fr: 'Complète : Le chat est ___ la table.', en: 'The cat is under the table.' },
            answer: 'sous',
            accept: ['sous'],
            explanation: { darija: 'sous = تحت. sur = فوق. sous la table = تحت الطابلة.', fr: 'sous = sous / under. sur = sur / on.', en: 'sous = under, sur = on.' },
          },
          {
            id: 'fr-a1-2-e3',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'Elle va ___ ma mère.', fr: 'Elle va ___ ma mère.', en: 'She is going to my mother’s.' },
            options: [
              { text: 'à' },
              { text: 'chez' },
              { text: 'dans' },
              { text: 'sur' },
            ],
            answer: 1,
            explanation: { darija: '«chez» كتستعمل للناس: chez ma mère = عند ماما.', fr: '« chez » s’emploie pour les personnes.', en: '"chez" is used for people.' },
          },
          {
            id: 'fr-a1-2-e4',
            type: 'translate',
            xp: 10,
            prompt: { fr: 'I have a sister.', en: 'I have a sister.' },
            answer: "j'ai une soeur",
            accept: ['une soeur', "j'ai une soeur", "j'ai une sœur", "j'ai une soeurs", 'j\'ai une soeur'],
            explanation: { darija: 'فـ الفرنسية كنسميها غير «une soeur» بلا ما نقولو « mon nom ».', fr: 'On donne directement le nom : une soeur.', en: 'In French you just say the noun: une soeur.' },
          },
          {
            id: 'fr-a1-2-e5',
            type: 'listen',
            xp: 15,
            audio: 'fr-FR',
            audioText: 'Je prends le train pour Paris.',
            prompt: { fr: 'Écoute. Où va-t-il ?', en: 'Listen. Where is he going?' },
            options: [
              { text: 'À Lyon' },
              { text: 'À Paris' },
              { text: 'À Casablanca' },
              { text: 'À Rabat' },
            ],
            answer: 1,
            explanation: { darija: '«Je prends le train pour Paris» = غادي نركب الطوموبيس لـParis.', fr: '« Je prends le train pour Paris » = je vais à Paris en train.', en: 'It means "I am taking the train to Paris".' },
          },
        ],
      },
      {
        id: 'fr-a1-3',
        order: 3,
        icon: '\u{1F6D2}',
        xp: 50,
        duration: 10,
        title: {
          native: 'Au marché et au restaurant',
          darija: 'فـ السوق و المطعم',
          ar: 'في السوق والمطعم',
          fr: 'Au marché et au restaurant',
          en: 'At the market and restaurant',
        },
        subtitle: {
          darija: 'الطعام، الأرقام، وطلب بثمن',
          ar: 'الطعام والأرقام والطلب',
          fr: 'Nourriture et commander',
          en: 'Food and ordering',
        },
        intro: {
          darija: 'فرنسا عندها **le marché** (السوق) ديال الصباح، و**la boulangerie** (المخبزة). فهاد الدرس غادي نتعلمو كيفاش تطلب السعر والطلب فـ المطعم.',
          ar: 'في فرنسا يوجد السوق الصباحي والمخبزة. نتعلم هنا طلب السعر وطلب الطعام.',
          fr: 'En France, il y a le marché du matin et la boulangerie. Ici, on apprend à commander.',
        },
        sections: [
          {
            type: 'text',
            body: {
              fr: "**Commander** :\n* Je voudrais un café, s’il vous plaît. = I would like a coffee, please.\n* **L'addition, s'il vous plaît.** = The bill, please.\n* **C'est combien ?** = How much is it?\n\n**Les nombres 0-20** : zéro, un, deux, trois, quatre, cinq, six, sept, huit, neuf, dix, onze, douze, treize, quatorze, quinze, seize, dix-sept, dix-huit, dix-neuf, vingt.",
              darija: '**كيفاش تطلب:**\n* **Je voudrais un café, s’il vous plaît** = بغيت قهوة من فضلك.\n* **L’addition, s’il vous plaît** = الحساب من فضلك.\n* **C’est combien** = بشحال؟\n\n**الأرقام من 0 لـ 20:** zéro، un، deux، trois، quatre، cinq، six، sept، huit، neuf، dix، onze، douze، treize، quatorze، quinze، seize، dix-sept، dix-huit، dix-neuf، vingt.',
              ar: 'الأرقام الفرنسية من 0 إلى 20، واستخدام je voudrais للطلب المهذب.',
            },
          },
        ],
        examples: [
          {
            source: "Je voudrais un thé à la menthe, s’il vous plaît.",
            translation: { darija: 'بغيت أتاي بالنعناع من فضلك.', ar: 'أودّ شايًا بالنعناع من فضلك.', fr: 'Je voudrais un thé à la menthe, s’il vous plaît.', en: 'I would like a mint tea, please.' },
            audio: 'fr-FR',
          },
          {
            source: "Ça fait combien, s’il vous plaît ?",
            translation: { darija: 'شحال هاد الشي من فضلك؟', ar: 'كم الثمن من فضلك؟', fr: 'Ça fait combien, s’il vous plaît ?', en: 'How much is that, please?' },
            audio: 'fr-FR',
          },
          {
            source: "L'addition, s'il vous plaît !",
            translation: { darija: 'الحساب من فضلك!', ar: 'الحساب من فضلك!', fr: 'L’addition, s’il vous plaît !', en: 'The bill, please!' },
            audio: 'fr-FR',
          },
        ],
        vocab: [
          { word: 'le pain', audio: 'fr-FR', translation: { darija: 'الخبز', ar: 'الخبز', fr: 'le pain', en: 'bread' } },
          { word: 'le fromage', audio: 'fr-FR', translation: { darija: 'الجبنة', ar: 'الجبن', fr: 'le fromage', en: 'cheese' } },
          { word: 'le café', audio: 'fr-FR', translation: { darija: 'القهوة', ar: 'القهوة', fr: 'le café', en: 'coffee' } },
          { word: 'le thé', audio: 'fr-FR', translation: { darija: 'أتاي', ar: 'الشاي', fr: 'le thé', en: 'tea' } },
          { word: "l'addition", audio: 'fr-FR', translation: { darija: 'الحساب', ar: 'الفاتورة', fr: 'l’addition', en: 'the bill' } },
          { word: 'je voudrais', audio: 'fr-FR', translation: { darija: 'بغيت (مهذب)', ar: 'أودّ', fr: 'je voudrais', en: 'I would like' } },
          { word: 's’il vous plaît', audio: 'fr-FR', translation: { darija: 'من فضلك', ar: 'من فضلك', fr: 's’il vous plaît', en: 'please' } },
          { word: 'le marché', audio: 'fr-FR', translation: { darija: 'السوق', ar: 'السوق', fr: 'le marché', en: 'the market' } },
        ],
        exercises: [
          {
            id: 'fr-a1-3-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'Un café, ___ vous plaît.', fr: 'Un café, ___ vous plaît.', en: 'A coffee, please.' },
            options: [
              { text: 'si' },
              { text: 'il' },
              { text: 'si l’' },
              { text: 'si y’' },
            ],
            answer: 0,
            explanation: { darija: 'العبارة: s’il vous plaît (s + il).', fr: 'La formule : « s’il vous plaît » (s + il).', en: 'The phrase is "s’il vous plaît".' },
          },
          {
            id: 'fr-a1-3-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'Combien ___ le fromage ?', fr: 'Combien ___ le fromage ?', en: 'How much is the cheese?' },
            answer: 'coûte',
            accept: ['coûte', 'coute', 'coûtes'],
            explanation: { darija: '«Combien coûte…؟» = بشحال ثمن؟', fr: '« Combien coûte… ? » = combien ça fait ?', en: '"Combien coûte…?" asks for a price.' },
          },
          {
            id: 'fr-a1-3-e3',
            type: 'listen',
            xp: 15,
            audio: 'fr-FR',
            audioText: "Je voudrais l'addition, s'il vous plaît.",
            prompt: { fr: 'Écoute. Que veut-il ?', en: 'Listen. What does he want?' },
            options: [
              { text: 'La carte' },
              { text: 'L’addition' },
              { text: 'Un café' },
              { text: 'Le menu' },
            ],
            answer: 1,
            explanation: { darija: 'l’addition = الحساب / الفاتورة.', fr: '« l’addition » = la facture.', en: '"l’addition" means the bill.' },
          },
          {
            id: 'fr-a1-3-e4',
            type: 'translate',
            xp: 10,
            prompt: { fr: 'I would like a coffee, please.', en: 'I would like a coffee, please.' },
            answer: 'je voudrais un café, s’il vous plaît',
            accept: ['je voudrais un café s’il vous plaît', 'un café s’il vous plaît', 'je voudrais un cafe s il vous plait'],
            explanation: { darija: '“Je voudrais” أرق من “Je veux”.', fr: '« Je voudrais » est plus poli que « je veux ».', en: '"Je voudrais" is more polite than "je veux".' },
          },
        ],
      },
    ],
  },
  {
    level: 'A2',
    lessons: [
      {
        id: 'fr-a2-1',
        order: 1,
        icon: '\u{1F4D8}',
        xp: 70,
        duration: 12,
        title: {
          native: 'Chercher un emploi',
          darija: 'البحث على خدمة',
          ar: 'البحث عن عمل',
          fr: 'Chercher un emploi',
          en: 'Looking for a job',
        },
        subtitle: {
          darija: 'الـ CV، l’entretien، و la lettre de motivation',
          ar: 'السيرة الذاتية والمقابلة',
          fr: 'CV et entretien',
          en: 'CV and interview',
        },
        intro: {
          darija: 'فـ فرنسا، **l’entretien** (المقابلة) عندها قواعد. خاصك تكون واضح، مهذب، و**confiant** — ماشي متعال.',
          ar: 'في فرنسا للمقابلة قواعد: الوضوح واللباقة والثقة.',
          fr: 'En France, l’entretien a des règles : soyez clair, poli et confiant.',
        },
        sections: [
          {
            type: 'text',
            body: {
              fr: "**Les questions classiques :**\n* *Parlez-moi de vous.* = Parlez-moi de vous.\n* *Pourquoi ce poste ?* = Pourquoi cette offre ?\n* *Quels sont vos points forts ?* = Quelles sont vos qualités ?\n* *Où vous voyez-vous dans 5 ans ?*\n\n**Verbes utiles :** postuler (to apply), publier (to publish), signer (to sign), un entretien (an interview), une expérience (experience), trouver un CDI (a permanent job).",
              darija: '**الأسئلة الكلاسيكية:**\n* حكي ليا على راسك.\n* علاش هاد الخدمة؟\n* شنو نقاط القوة ديالك؟\n* فين كتشوف راسك بعد 5 سنين؟\n\n**أفعال مفيدة:** يتسجل (postuler)، يعلن (publier)، موقّع (signer)، مقابلة (entretien)، خبرة (expérience)، يلقى خدمة دائمة (CDI).',
              ar: 'الأسئلة الشائعة في مقابلة العمل بالفرنسية، وأهم الأفعال postuler و trouver.',
            },
          },
        ],
        examples: [
          {
            source: "Je suis motivated et j'aime travailler en équipe.",
            translation: { darija: 'أنا متحمس وكنحب نخدم فـ فريق.', ar: 'أنا متحمس وأحب العمل ضمن فريق.', fr: 'Je suis motivé et j’aime travailler en équipe.', en: 'I am motivated and I like working in a team.' },
            audio: 'fr-FR',
          },
          {
            source: "J'ai trois ans d'expérience en restauration.",
            translation: { darija: 'عندي تلات سنين ديال الخبرة فـ المطاعم.', ar: 'لدي ثلاث سنوات خبرة في المطاعم.', fr: 'J’ai trois ans d’expérience en restauration.', en: 'I have three years of experience in restaurants.' },
            audio: 'fr-FR',
          },
          {
            source: "Je postule pour le poste de vendeur.",
            translation: { darija: 'أنا مسجل باش نخدم بحال بائع.', ar: 'أتقدم لوظيفة بائع.', fr: 'Je postule pour le poste de vendeur.', en: 'I am applying for the sales position.' },
            audio: 'fr-FR',
          },
        ],
        vocab: [
          { word: 'un emploi', audio: 'fr-FR', translation: { darija: 'خدمة / عمل', ar: 'وظيفة', fr: 'un emploi', en: 'a job' } },
          { word: 'postuler', audio: 'fr-FR', translation: { darija: 'يسجل فـ', ar: 'يتقدم بطلب', fr: 'postuler', en: 'to apply' } },
          { word: 'un entretien', audio: 'fr-FR', translation: { darija: 'مقابلة', ar: 'مقابلة', fr: 'un entretien', en: 'an interview' } },
          { word: "l'expérience", audio: 'fr-FR', translation: { darija: 'الخبرة', ar: 'الخبرة', fr: 'l’expérience', en: 'experience' } },
          { word: 'le salaire', audio: 'fr-FR', translation: { darija: 'الراتب', ar: 'الراتب', fr: 'le salaire', en: 'the salary' } },
          { word: 'motivé(e)', audio: 'fr-FR', translation: { darija: 'متحمس', ar: 'متحمس', fr: 'motivé(e)', en: 'motivated' } },
          { word: 'le CV', audio: 'fr-FR', translation: { darija: 'السيرة الذاتية', ar: 'السيرة الذاتية', fr: 'le CV', en: 'the CV' } },
          { word: 'candidater', audio: 'fr-FR', translation: { darija: 'يترشح', ar: 'يرشح نفسه', fr: 'candidater', en: 'to apply' } },
        ],
        exercises: [
          {
            id: 'fr-a2-1-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: '___ que vous aimez travailler en équipe ?', fr: '___ que vous aimez travailler en équipe ?', en: 'What do you like about teamwork?' },
            options: [
              { text: 'Qualités' },
              { text: 'Pourquoi' },
              { text: 'Où' },
              { text: 'Combien' },
            ],
            answer: 1,
            explanation: { darija: '«Pourquoi…؟» = علاش؟', fr: '« Pourquoi… ? » = pour quelle raison ?', en: '"Pourquoi" asks why.' },
          },
          {
            id: 'fr-a2-1-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: "J'ai cinq ans d'______ .", fr: 'Complète : J’ai cinq ans d’______ .', en: 'I have five years of experience.' },
            answer: 'expérience',
            accept: ['expérience', 'experience', 'expérience.'],
            explanation: { darija: '«avoir de l’expérience» = عندك خبرة.', fr: '« avoir de l’expérience » = avoir de l’ancienneté.', en: '"avoir de l’expérience" = to have experience.' },
          },
          {
            id: 'fr-a2-1-e3',
            type: 'translate',
            xp: 10,
            prompt: { fr: 'I am applying for the job.', en: 'I am applying for the job.' },
            answer: 'je postule pour le poste',
            accept: ['je postule', 'postule', 'je postule pour le poste', 'je postule a ce poste', 'je candidate'],
            explanation: { darija: '«Je postule» = أنا مسجل (فـ الخدمة).', fr: '« Je postule » = je dépose ma candidature.', en: '"Je postule" = I am applying.' },
          },
          {
            id: 'fr-a2-1-e4',
            type: 'listen',
            xp: 15,
            audio: 'fr-FR',
            audioText: "Je suis disponible immédiatement.",
            prompt: { fr: 'Écoute. Quand peut-il commencer ?', en: 'Listen. When can he start?' },
            options: [
              { text: 'Dans un mois' },
              { text: 'Maintenant' },
              { text: 'Dans un an' },
              { text: 'Il ne sait pas' },
            ],
            answer: 1,
            explanation: { darija: '«immédiatement» = حالا / دغيا.', fr: '« immédiatement » = tout de suite.', en: '"immédiatement" means right away.' },
          },
        ],
      },
      {
        id: 'fr-a2-2',
        order: 2,
        icon: '\u{1F3E0}',
        xp: 70,
        duration: 11,
        title: {
          native: 'La vie administrative',
          darija: 'الوراقيات والإدارة',
          ar: 'الإجراءات الإدارية',
          fr: 'La vie administrative',
          en: 'Paperwork and admin',
        },
        subtitle: {
          darija: 'الـ logement، la banque، و l’assurance',
          ar: 'السكن والبنك والتأمين',
          fr: 'Logement, banque et assurance',
          en: 'Housing, bank and insurance',
        },
        intro: {
          darija: 'الوراقيات فـ فرنسا كتسمى **l’administration**. خاصك تعرف: **le logement**، **la banque**، **l’assurance**، و **le centre des impôts**.',
          ar: 'الإجراءات الإدارية في فرنسا: السكن والبنك والتأمين ومصلحة الضرائب.',
          fr: 'Les démarches en France : le logement, la banque, l’assurance et le centre des impôts.',
        },
        sections: [
          {
            type: 'text',
            body: {
              fr: "**Documents utiles :**\n* une pièce d’identité (carte d’identité ou passeport)\n* un justificatif de domicile (facture EDF, avis d’imposition)\n* un RIB (Relevé d’Identité Bancaire)\n* une attestation d’assurance\n\n**Verbes utiles :** emménager (to move in), envoyer (to send), attendre (to wait), apprendre (to learn).",
              darija: '**الوثائق المهمة:**\n* une pièce d’identité (كارطة التعريف ولا جواز السفر)\n* un justificatif de domicile (فاتورة الكهرباء ولا الضريبة)\n* un RIB (رقم الحساب البنكي)\n* une attestation d’assurance (شهادة التأمين)\n\n**أفعال:** déménager (ينتقل سكن)، attendre (يسنى)، envoyer (يبعت)، apprendre (يتعلم).',
              ar: 'الوثائق الضرورية في فرنسا: بطاقة تعريف، إثبات سكن، حساب بنكي، شهادة تأمين.',
            },
          },
        ],
        examples: [
          {
            source: "J'ai besoin d'un justificatif de domicile.",
            translation: { darija: 'خاصني attestation ديال السكن.', ar: 'أحتاج إلى إثبات سكن.', fr: 'J’ai besoin d’un justificatif de domicile.', en: 'I need proof of address.' },
            audio: 'fr-FR',
          },
          {
            source: "Il faut envoyer le dossier avant le 15.",
            translation: { darija: 'خاصك تبعت الملف قبل 15.', ar: 'يجب إرسال الملف قبل الخامس عشر.', fr: 'Il faut envoyer le dossier avant le 15.', en: 'You must send the file before the 15th.' },
            audio: 'fr-FR',
          },
        ],
        vocab: [
          { word: 'le dossier', audio: 'fr-FR', translation: { darija: 'الملف', ar: 'الملف', fr: 'le dossier', en: 'the file' } },
          { word: 'le justificatif de domicile', audio: 'fr-FR', translation: { darija: 'إثبات السكن', ar: 'إثبات سكن', fr: 'le justificatif de domicile', en: 'proof of address' } },
          { word: 'la carte d’identité', audio: 'fr-FR', translation: { darija: 'كارطة التعريف', ar: 'بطاقة التعريف', fr: 'la carte d’identité', en: 'ID card' } },
          { word: 'la banque', audio: 'fr-FR', translation: { darija: 'البنك', ar: 'البنك', fr: 'la banque', en: 'the bank' } },
          { word: "l'assurance", audio: 'fr-FR', translation: { darija: 'التأمين', ar: 'التأمين', fr: 'l’assurance', en: 'insurance' } },
          { word: 'envoyer', audio: 'fr-FR', translation: { darija: 'يبعت', ar: 'يرسل', fr: 'envoyer', en: 'to send' } },
          { word: 'attendre', audio: 'fr-FR', translation: { darija: 'يسنى', ar: 'ينتظر', fr: 'attendre', en: 'to wait' } },
          { word: 'déménager', audio: 'fr-FR', translation: { darija: 'ينتقل سكن', ar: 'ينتقل سكنًا', fr: 'déménager', en: 'to move house' } },
        ],
        exercises: [
          {
            id: 'fr-a2-2-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'Un ___ de domicile prouve où tu habites.', fr: 'Un ___ de domicile prouve où tu habites.', en: 'A proof of address shows where you live.' },
            options: [
              { text: 'RIB' },
              { text: 'justificatif' },
              { text: 'passeport' },
              { text: 'menu' },
            ],
            answer: 1,
            explanation: { darija: '«un justificatif de domicile» = إثبات السكن.', fr: '« un justificatif de domicile » = une preuve d’adresse.', en: '"justificatif de domicile" is proof of address.' },
          },
          {
            id: 'fr-a2-2-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: "Il faut ___ le dossier à l'administration.", fr: 'Complète : Il faut ___ le dossier.', en: 'You must send the file.' },
            answer: 'envoyer',
            accept: ['envoyer', 'envoyez', 'transmettre'],
            explanation: { darija: '«envoyer» = يبعت. التصريف: j’envoie، tu envoies، il envoie.', fr: '« envoyer » = expédier.', en: '"envoyer" means to send.' },
          },
          {
            id: 'fr-a2-2-e3',
            type: 'translate',
            xp: 10,
            prompt: { fr: 'I need my passport.', en: 'I need my passport.' },
            answer: "j'ai besoin de mon passeport",
            accept: ['j’ai besoin de mon passeport', 'j’ai besoin du passeport', 'je besoin de mon passeport', 'il me faut mon passeport'],
            explanation: { darija: '«avoir besoin de» = خاصك. ديما + de.', fr: '« avoir besoin de » + article possessif.', en: '"avoir besoin de" + possessive adjective.' },
          },
        ],
      },
    ],
  },
]
