/* lint-allow: Krankenkasse Schmerzen Rezept Apotheke Arzt Fieber Bauch Kopf Bein Hand Herz Husten brauchen brauche */
export const germanLessons = [
  {
    level: 'A1',
    lessons: [
      {
        id: 'de-a1-1',
        order: 1,
        icon: '\u{1F44B}',
        xp: 50,
        duration: 8,
        title: {
          native: 'Ich heiße... und ich komme aus...',
          darija: 'سميتي... و جيت من...',
          ar: 'اسمي... وأنا من...',
          fr: 'Je m’appelle… et je viens de…',
          en: 'My name is… and I am from…',
        },
        subtitle: {
          darija: 'الأفعال و die / der / das',
          ar: 'الأفعال وأدوات التعريف',
          fr: 'Verbes et articles die/der/das',
          en: 'Verbs and the articles',
        },
        intro: {
          darija: 'الألمانية صعيبة ولكن مربحة بزاف. أهم حاجة: كاين **der** (مذكر)، **die** (مؤنث)، **das** (محايد)، و **die** (جمع). خاصك تحفظهم مع الكلمة.',
          ar: 'في الألمانية أدوات التعريف der و die و das، و die للمذكر الجمع. يجب حفظها مع الكلمة.',
          fr: 'Les articles allemands : der, die, das — et die au pluriel. À apprendre avec le nom.',
        },
        sections: [
          {
            type: 'text',
            body: {
              de: '**sein** = to be: ich **bin**, du **bist**, er/sie/es **ist**, wir **sind**, ihr **seid**, sie/Sie **sind**.\n**haben** = to have: ich **habe**, du **hast**, er/sie/es **hat**, wir **haben**, ihr **habt**, sie/Sie **haben**.\n\n*Ich heiße Amine. Ich komme aus Marokko. Ich wohne in München.*\n\n**Wo?** = Where? **Wie?** = How? **Was?** = What? **Warum?** = Why?',
              darija: '**sein** = يكون: ich bin، du bist، er ist، wir sind.\n**haben** = عند: ich habe، du hast، er hat، wir haben.\n\n*Ich heiße Amine* = سمّيتي أمين. *Ich komme aus Marokko* = جيت من المغرب. *Ich wohne in München* = ساكن فـ ميونخ.\n\n**Wo** = فين؟ **Wie** = كيفاش؟ **Was** = شنو؟ **Warum** = علاش؟',
              ar: 'الأفعال sein و haben مع تصريفاتها. Wo = أين، Wie = كيف، Was = ماذا، Warum = لماذا.',
              fr: 'sein = être, haben = avoir. Wo = où, Wie = comment, Was = quoi, Warum = pourquoi.',
            },
          },
          {
            type: 'text',
            body: {
              de: '**Capital letters are compulsory:** every noun is written with a big letter.\n\n**der** → masculine: der Vater, der Tisch\n**die** → feminine: die Mutter, die Stadt\n**das** → neuter: das Kind, das Haus\n**die** → plural: die Kinder, die Städte\n\n**Accusative:** the case you need for “I want…”.\nder Mann → **den** Mann · die Frau → **die** Frau · das Kind → **das** Kind',
              darija: '**كل الأسماء خاصها حرف كبير** فـ الكتابة الألمانية.\n\n**der** = مذكر (der Tisch)، **die** = مؤنث (die Mutter)، **das** = محايد (das Haus)، **die** = جمع (die Kinder).\n\n**حالة المفعول:** إلا بغيتي حاجة، كتبدل der → den. مثل: der Mann → den Mann.',
              ar: 'الأسماءASY German nouns are capitalised. der للمذكر، die للمؤنث والجمع، das للمحيّد. في حالة المفعول يتحول der إلى den.',
              fr: 'Tous les noms allemands prennent une majuscule. der (masc.), die (fém. et pluriel), das (neutre). Accusatif : der → den.',
            },
          },
        ],
        examples: [
          {
            source: 'Guten Tag! Ich heiße Salma.',
            translation: { darija: 'صباح الخير! سمّيتي سلمى.', ar: 'صباح الخير! اسمي سلمى.', fr: 'Bonjour ! Je m’appelle Salma.', en: 'Good day! My name is Salma.' },
            audio: 'de-DE',
          },
          {
            source: 'Ich wohne in Berlin und ich habe zwei Brüder.',
            translation: { darija: 'ساكن فـ برلين و عندي جوج خاوة.', ar: 'أعيش في برلين ولدي أخوان.', fr: 'J’habite à Berlin et j’ai deux frères.', en: 'I live in Berlin and I have two brothers.' },
            audio: 'de-DE',
          },
          {
            source: 'Woher kommen Sie?',
            translation: { darija: 'واش نتا منين؟', ar: 'من أين أنت؟', fr: 'D’où venez-vous ?', en: 'Where are you from?' },
            audio: 'de-DE',
          },
        ],
        vocab: [
          { word: 'das Haus', audio: 'de-DE', translation: { darija: 'البيت', ar: 'المنزل', fr: 'la maison', en: 'the house' } },
          { word: 'die Stadt', audio: 'de-DE', translation: { darija: 'المدينة', ar: 'المدينة', fr: 'la ville', en: 'the city' } },
          { word: 'der Bruder', audio: 'de-DE', translation: { darija: 'خويا', ar: 'أخ', fr: 'le frère', en: 'the brother' } },
          { word: 'die Schwester', audio: 'de-DE', translation: { darija: 'أخت', ar: 'أخت', fr: 'la sœur', en: 'the sister' } },
          { word: 'die Arbeit', audio: 'de-DE', translation: { darija: 'الخدمة', ar: 'العمل', fr: 'le travail', en: 'the work' } },
          { word: 'wohnen', audio: 'de-DE', translation: { darija: 'ساكن', ar: 'يسكن', fr: 'habiter', en: 'to live' } },
          { word: 'heißen', audio: 'de-DE', translation: { darija: 'سميتي', ar: 'يُدعى', fr: 's’appeler', en: 'to be called' } },
          { word: 'danke', audio: 'de-DE', translation: { darija: 'شكراً', ar: 'شكرًا', fr: 'merci', en: 'thank you' } },
        ],
        exercises: [
          {
            id: 'de-a1-1-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'Ich ___ Amine.', fr: 'Je ___ Amine.', en: 'I am Amine.' },
            options: [
              { text: 'bin' },
              { text: 'bist' },
              { text: 'ist' },
              { text: 'sind' },
            ],
            answer: 0,
            explanation: { darija: 'مع ich كنسميو bin.', fr: 'Avec ich : bin.', en: 'With "ich" the verb is "bin".' },
          },
          {
            id: 'de-a1-1-e2',
            type: 'mcq',
            xp: 10,
            prompt: { native: '___ Mutter', fr: '___ Mutter', en: 'the mother' },
            options: [
              { text: 'der' },
              { text: 'die' },
              { text: 'das' },
              { text: 'den' },
            ],
            answer: 1,
            explanation: { darija: 'die Mutter = الأم (مؤنث).', fr: 'die Mutter = la mère (féminin).', en: '"Mutter" is feminine, so "die".' },
          },
          {
            id: 'de-a1-1-e3',
            type: 'fill',
            xp: 10,
            prompt: { native: 'Ich ___ zwei Brüder.', fr: 'J’ai ___ frères.', en: 'I have two brothers.' },
            answer: 'habe',
            accept: ['habe', 'haben'],
            explanation: { darija: 'مع ich: habe. مع er: hat. مع wir: haben.', fr: 'ich habe, er hat, wir haben.', en: 'ich habe, er hat, wir haben.' },
          },
          {
            id: 'de-a1-1-e4',
            type: 'translate',
            xp: 10,
            prompt: { en: 'I am from Morocco.', fr: 'Je viens du Maroc.' },
            answer: 'ich komme aus marokko',
            accept: ['ich komme aus marokko', 'ich komme aus marokko.', 'komme aus marokko', 'ich komme aus marokko!'],
            explanation: { darija: '«ich komme aus» = جيت من. «aus» ديما مع الأوطان.', fr: '« ich komme aus » + pays, toujours avec aus.', en: '"ich komme aus" + country, always with aus.' },
          },
          {
            id: 'de-a1-1-e5',
            type: 'listen',
            xp: 15,
            audio: 'de-DE',
            audioText: 'Ich wohne in München.',
            prompt: { fr: 'Écoute. Où habite-t-il ?', en: 'Listen. Where does he live?' },
            options: [
              { text: 'À Berlin' },
              { text: 'À Munich' },
              { text: 'À Hambourg' },
              { text: 'À Cologne' },
            ],
            answer: 1,
            explanation: { darija: 'München = ميونخ (جنوب ألمانيا).', fr: 'München = Munich.', en: 'München is Munich.' },
          },
          {
            id: 'de-a1-1-e6',
            type: 'speak',
            xp: 20,
            audio: 'de-DE',
            audioText: 'Guten Tag, ich heiße Youssef und ich komme aus Marokko.',
            prompt: { fr: 'Dis : « Guten Tag, ich heiße Youssef und ich komme aus Marokko. »', en: 'Say: "Good day, my name is Youssef and I come from Morocco."' },
            explanation: { darija: 'انتبه للـ ch فـ ich و für.', fr: 'Attention au ch de ich et au ü de für.', en: 'Mind the "ch" in ich and the "ü" in für.' },
          },
        ],
      },
      {
        id: 'de-a1-2',
        order: 2,
        icon: '\u{1F9D7}',
        xp: 50,
        duration: 9,
        title: {
          native: 'Beim Arzt und in der Apotheke',
          darija: 'عند الطبيب و الصيدلية',
          ar: 'عند الطبيب والصيدلية',
          fr: 'Chez le médecin et à la pharmacie',
          en: 'At the doctor and pharmacy',
        },
        subtitle: {
          darija: 'الألم والأدوية و das Verb im Akkativ',
          ar: 'الألم والأدوية',
          fr: 'La douleur et les médicaments',
          en: 'Pain and medicines',
        },
        intro: {
          darija: 'فـ ألمانيا، الصحة ماشي مجانية: خاص **die Krankenkasse** (التأمين الصحي). من أهم الكلمات: **Schmerzen** (وجع)، **das Rezept** (الوصفة الطبية).',
          ar: 'في ألمانيا التأمين الصحي إلزامي. من أهم الكلمات: Schmerzen (ألم) و das Rezept (وصفة).',
          fr: 'En Allemagne, l’assurance maladie est obligatoire. Schmerzen = douleur, das Rezept = ordonnance.',
        },
        sections: [
          {
            type: 'text',
            body: {
              de: '**Useful phrases:**\n* *Ich habe Schmerzen.* = I have pain.\n* *Mein Kopf tut weh.* = My head hurts.\n* *Mein Bauch tut weh.* = My stomach hurts.\n* *Ich habe Fieber.* = I have a fever.\n* *Ich brauche ein Rezept.* = I need a prescription.\n* *Haben Sie etwas gegen Husten?* = Do you have something for a cough?\n\n**Der Körper:** der Kopf (head), die Hand (hand), das Bein (leg), der Bauch (stomach), das Herz (heart).',
              darija: '**عبارات مهمة:**\n* Ich habe Schmerzen = عندي وجع.\n* Mein Kopf tut weh = راسي كيوجعني.\n* Ich habe Fieber = عندي حرارة.\n* Ich brauche ein Rezept = خاصني وصفة طبية.\n\n**الجسم:** der Kopf (الراس)، die Hand (اليد)، das Bein (الرجل)، der Bauch (البطن)، das Herz (القلب).',
              ar: 'العبارات الطبية بالألمانية. der Kopf = الرأس، die Hand = اليد، das Bein = الساق.',
              fr: 'Les phrases médicales : j’ai mal, j’ai de la fièvre. der Kopf = la tête, die Hand = la main.',
            },
          },
        ],
        examples: [
          {
            source: 'Mein Bauch tut weh.',
            translation: { darija: 'المعدة ديالي كتوجعني.', ar: 'أ stomachي يؤلمني.', fr: 'J’ai mal au ventre.', en: 'My stomach hurts.' },
            audio: 'de-DE',
          },
          {
            source: 'Ich brauche ein Rezept für die Apotheke.',
            translation: { darija: 'خاصني وصفة طبية للصيدلية.', ar: 'أحتاج وصفة طبية للصيدلية.', fr: 'Il me faut une ordonnance pour la pharmacie.', en: 'I need a prescription for the pharmacy.' },
            audio: 'de-DE',
          },
        ],
        vocab: [
          { word: 'die Schmerzen', audio: 'de-DE', translation: { darija: 'الوجع', ar: 'الألم', fr: 'la douleur', en: 'the pain' } },
          { word: 'das Fieber', audio: 'de-DE', translation: { darija: 'الحرارة', ar: 'الحمى', fr: 'la fièvre', en: 'the fever' } },
          { word: 'das Rezept', audio: 'de-DE', translation: { darija: 'الوصفة الطبية', ar: 'الوصفة الطبية', fr: 'l’ordonnance', en: 'the prescription' } },
          { word: 'die Apotheke', audio: 'de-DE', translation: { darija: 'الصيدلية', ar: 'الصيدلية', fr: 'la pharmacie', en: 'the pharmacy' } },
          { word: 'die Krankenkasse', audio: 'de-DE', translation: { darija: 'التأمين الصحي', ar: 'التأمين الصحي', fr: 'la caisse d’assurance maladie', en: 'the health insurance' } },
          { word: 'der Arzt', audio: 'de-DE', translation: { darija: 'الطبيب', ar: 'الطبيب', fr: 'le médecin', en: 'the doctor' } },
          { word: 'brauchen', audio: 'de-DE', translation: { darija: 'يحتاج', ar: 'يحتاج', fr: 'avoir besoin', en: 'to need' } },
        ],
        exercises: [
          {
            id: 'de-a1-2-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'Ich ___ Fieber.', fr: 'J’ai ___ fièvre.', en: 'I have a fever.' },
            options: [
              { text: 'habe' },
              { text: 'hat' },
              { text: 'haben' },
              { text: 'bin' },
            ],
            answer: 0,
            explanation: { darija: 'مع ich: habe. «Fieber» مؤنث (die Fieber) وكتبقى فـ di feminine.', fr: 'ich habe, er hat.', en: 'With "ich" it is "habe".' },
          },
          {
            id: 'de-a1-2-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'Mein Kopf ___ weh.', fr: 'Complète : Mein Kopf ___ weh.', en: 'My head hurts.' },
            answer: 'tut',
            accept: ['tut', 'tut mir'],
            explanation: { darija: '«tut weh» = كيوجع. ماشي hurt.', fr: 'On dit « tut weh », pas « hurt ».', en: 'German uses "tut weh", not "hurt".' },
          },
          {
            id: 'de-a1-2-e3',
            type: 'translate',
            xp: 10,
            prompt: { en: 'I need a prescription.', fr: 'Il me faut une ordonnance.' },
            answer: 'ich brauche ein rezept',
            accept: ['ich brauche ein rezept', 'ich brauche ein rezept.', 'ich brauche rezept', 'brauche ein rezept'],
            explanation: { darija: '«brauchen» = يحتاج. و«das» كتحول لـ **ein** فـ حالة المفعول.', fr: 'das devient ein à l’accusatif.', en: 'The neuter article "das" becomes "ein" in the accusative.' },
          },
          {
            id: 'de-a1-2-e4',
            type: 'listen',
            xp: 15,
            audio: 'de-DE',
            audioText: 'Ich habe Schmerzen im Bauch.',
            prompt: { fr: 'Écoute. Où est la douleur ?', en: 'Listen. Where is the pain?' },
            options: [
              { text: 'La tête' },
              { text: 'Le ventre' },
              { text: 'La main' },
              { text: 'La jambe' },
            ],
            answer: 1,
            explanation: { darija: 'der Bauch = البطن.', fr: 'der Bauch = le ventre.', en: '"der Bauch" means stomach / البطن.' },
          },
        ],
      },
    ],
  },
]
