export const darijaLessons = [
  {
    level: 'A1',
    lessons: [
      {
        id: 'darija-a1-1',
        order: 1,
        icon: '\u{1F44B}',
        xp: 50,
        duration: 8,
        title: {
          native: 'السلام عليكم — شكون نتا؟',
          darija: 'السلام عليكم — شكون نتا؟',
          ar: 'السلام عليكم — من أنت؟',
          fr: 'Salut — qui es-tu ?',
          en: 'Hello — who are you?',
        },
        subtitle: {
          darija: 'التعارف، التحية، و«كيفاش كتدير اسمك»',
          ar: 'التحية والتعارف',
          fr: 'Salutations et présentation',
          en: 'Greetings and introductions',
        },
        intro: {
          darija: 'فـ المغرب، حيت بال واحد كيقلب عليك بحال شي كلمة ع.pk — واش كتنطقها صحيح؟ غادي نتعلمو كيفاش نقولو «أنا فلان، واش천تي؟»',
          ar: 'نتعلم التحيات والتعارف بالدارجة، وهي المدخل لكل شيء آخر.',
          fr: "Apprendre à se présenter en darija : c'est la porte d'entrée de tout le reste.",
        },
        sections: [
          {
            type: 'text',
            body: {
              darija: 'فـ المغرب كاينة جوج ديال التحيات. **السلام عليكم** كتותسعمل فـ كل نهار، فأي بلاصة. و**أهلا** ولا **مرحبا بيك** كتوتسعمل فالاستقبال. الجواب ديال «السلام عليكم» هو «وعليكم السلام».',
              ar: 'في المغرب توجد تحيتان. «السلام عليكم» تُستخدم كل يوم في أي مكان. و«أهلا» أو «مرحبا بيك» عند الاستقبال. والرد على «السلام عليكم» هو «وعليكم السلام».',
              fr: "Au Maroc, il y a deux salutations. «السلام عليكم » (as-salāmu ʿalaykum) se dit tous les jours, partout. «أهلا » (ahlan) sert à accueillir. On répond « و عليكم السلام » (wa ʿalaykum as-salām).",
            },
          },
          {
            type: 'text',
            body: {
              darija: 'من بعد التحية، كنسولو على **الاسم**. فـ الدارجة ما كاينش «اسمي فلان» بحال العربية الفصحى — كنقولو غير **«أنا فلان»** ولا **«سمّيت فلان»**. و باش نسولو واحد على سميتو كنقولو: **«واش كتنسم؟»** ولا **«شنو كتنسم؟»**.',
              ar: 'بعد التحية نسأل عن الاسم. في الدارجة نقول «أنا فلان» أو «سميت فلان»، وللسؤال: «واش كتنسم؟» أو «شنو كتنسم؟».',
              fr: "Après la salutation, on demande le prénom. En darija on dit « أنا فلان » (ana fllan) ou « سميت فلان » (semmit fllan), et pour demander : « واش كتنسم؟ » (wash katsenom?) ou « شنو كتنسم؟ » (chno katsenom?).",
            },
          },
        ],
        examples: [
          {
            source: 'السلام عليكم! واش كتنسم؟',
            translit: 'as-salāmu ʿalaykum! wash katsenom?',
            translation: {
              darija: 'السلام عليكم! شنو كتنسم؟',
              ar: 'مرحبًا! ما اسمك؟',
              fr: 'Bonjour ! Quel est ton prénom ?',
              en: 'Hello! What is your name?',
            },
            audio: 'ar-MA',
          },
          {
            source: 'أنا سعاد. بغيت نعرفك.',
            translit: 'ana sou3ad. bghit n3refek.',
            translation: {
              darija: 'أنا سعاد، بغيت نعرفك.',
              ar: 'أنا سعاد، أود أن أتعرّف عليك.',
              fr: 'Je suis Souad, j’aimerais te connaître.',
              en: 'I am Souad, I would like to meet you.',
            },
            audio: 'ar-MA',
          },
          {
            source: 'واش كاين شي بلاصة فاش نتقاسو؟',
            translit: 'wash kayen chi blasa fin nteqassou?',
            translation: {
              darija: 'واش كاين شي بلاصة فاش نتقاسو؟',
              ar: 'هل يوجد مكان نلتقي فيه؟',
              fr: 'On peut se voir quelque part ?',
              en: 'Is there a place where we can meet?',
            },
            audio: 'ar-MA',
          },
        ],
        vocab: [
          { word: 'السلام عليكم', translit: 'as-salāmu ʿalaykum', audio: 'ar-MA', translation: { ar: 'السلام عليكم', fr: 'Bonjour', en: 'Hello' } },
          { word: 'وعليكم السلام', translit: 'wa ʿalaykum as-salām', audio: 'ar-MA', translation: { ar: 'وعليكم السلام', fr: 'Bonjour (réponse)', en: 'Hello (reply)' } },
          { word: 'مرحبا بيك', translit: 'mrhba bik', audio: 'ar-MA', translation: { ar: 'أهلاً بك', fr: 'Bienvenue', en: 'Welcome' } },
          { word: 'أنا', translit: 'ana', audio: 'ar-MA', translation: { ar: 'أنا', fr: 'je', en: 'I' } },
          { word: 'واش كتنسم؟', translit: 'wash katsenom?', audio: 'ar-MA', translation: { ar: 'ما اسمك؟', fr: 'Quel est ton prénom ?', en: 'What is your name?' } },
          { word: 'شنو', translit: 'chno', audio: 'ar-MA', translation: { ar: 'ماذا / ما', fr: 'quoi / qu’est-ce que', en: 'what' } },
          { word: 'بغيت', translit: 'bghit', audio: 'ar-MA', translation: { ar: 'أريد', fr: 'je veux', en: 'I want' } },
          { word: 'بلاصة', translit: 'blasa', audio: 'ar-MA', translation: { ar: 'مكان', fr: 'endroit / place', en: 'place' } },
        ],
        exercises: [
          {
            id: 'darija-a1-1-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'شنو كيعني «واش كتنسم؟»؟', fr: 'Que signifie « واش كتنسم؟ » ?', en: 'What does «واش كتنسم؟» mean?' },
            options: [
              { text: 'كيف حالك؟', audio: 'ar-MA' },
              { text: 'شنو كتنسم؟ (ما اسمك؟)', audio: 'ar-MA' },
              { text: 'فين ساكن؟', audio: 'ar-MA' },
              { text: 'واش بغيتي شي حاجة؟', audio: 'ar-MA' },
            ],
            answer: 1,
            explanation: {
            explanation: { darija: '«واش كتنسم؟» كتعني «واش هو الاسم ديالك؟» — يعني «ما اسمك؟».', fr: 'Cela veut dire « quel est ton prénom ? ».', en: 'It means "what is your name?".' },
              fr: 'Cela veut dire « quel est ton prénom ? ».',
              en: 'It means "what is your name?".',
            },
          },
          {
            id: 'darija-a1-1-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'كمّل: أنا ______. بغيت نعرفك.', fr: 'Complète : أنا ______ . بغيت نعرفك.', en: 'Complete: I am ______.' },
            answer: 'سعاد',
            accept: ['سعاد', 'souad', 'sou3ad', 'سعاد'],
            explanation: {
              darija: 'فـ الدارجة كنقدمو الاسم بلا «اسمي» ولا «سميت». غير «أنا سعاد».',
              fr: 'En darija on donne son prénom directement, sans « mon nom ».',
              en: 'In Darija you just say the name after "I am".',
            },
          },
          {
            id: 'darija-a1-1-e3',
            type: 'translate',
            xp: 10,
            prompt: { fr: 'Comment tu t’appelles ?', en: 'What is your name?' },
            answer: 'واش كتنسم',
            accept: ['واش كتنسم', 'واش كتنسم؟', 'شنو كتنسم', 'wash katsenom', 'chno katsenom'],
            explanation: {
              darija: 'الطريقتين خدامين: «واش كتنسم؟» و«شنو كتنسم؟».',
              fr: 'Les deux sont corrects.',
              en: 'Both forms are correct.',
            },
          },
          {
            id: 'darija-a1-1-e4',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'واحد قال ليك «السلام عليكم». شنو كيجاوب؟', fr: 'Quelqu’un te dit «السلام عليكم ». Tu réponds ?', en: 'Someone says hello to you. How do you reply?' },
            options: [
              { text: 'بسم الله', audio: 'ar-MA' },
              { text: 'وعليكم السلام', audio: 'ar-MA' },
              { text: 'صباح الخير', audio: 'ar-MA' },
              { text: 'بسلامة', audio: 'ar-MA' },
            ],
            answer: 1,
            explanation: {
              darija: 'الرد ديال «السلام عليكم» هو «وعليكم السلام».',
              fr: 'La réponse est « و عليكم السلام ».',
              en: 'The reply is "wa ʿalaykum as-salām".',
            },
          },
          {
            id: 'darija-a1-1-e5',
            type: 'listen',
            xp: 15,
            audio: 'ar-MA',
            audioText: 'بغيت نعرفك',
            prompt: { fr: 'Écoute. Que veut-il dire ?', en: 'Listen. What does it mean?' },
            options: [
              { text: 'Je veux te rencontrer' },
              { text: 'Je ne te connais pas' },
              { text: 'Où es-tu ?' },
              { text: 'Merci beaucoup' },
            ],
            answer: 0,
            explanation: {
              darija: '«بغيت نعرفك» = بغيت نتعرف عليك. كتستعملها مع الناس اللي كنعرفهم.',
              fr: '« بغيت نعرفك » = je voudrais te connaître.',
              en: 'It means "I would like to get to know you".',
            },
          },
          {
            id: 'darija-a1-1-e6',
            type: 'speak',
            xp: 20,
            audio: 'ar-MA',
            audioText: 'السلام عليكم، واش كتنسم؟',
            prompt: { fr: 'Dis à voix haute : « Bonjour, quel est ton prénom ? »', en: 'Say out loud: "Hello, what is your name?"' },
            explanation: {
              darija: 'سجّل صوتك وقارنو مع النموذج. فـهاد المستوى كافي.',
              fr: 'Enregistre-toi et compare avec le modèle.',
              en: 'Record yourself and compare with the model.',
            },
          },
        ],
      },
      {
        id: 'darija-a1-2',
        order: 2,
        icon: '\u{1F465}',
        xp: 50,
        duration: 9,
        title: {
        native: 'واش كاين؟ — العائلة والأصحاب',
          darija: 'العائلة والأصحاب',
          ar: 'العائلة والأصدقاء',
          fr: 'La famille et les amis',
          en: 'Family and friends',
        },
        subtitle: {
        darija: 'واش كاين؟ كيفاش كنسولو على العائلة؟',
          ar: 'أدوات التعريف والنفي',
          fr: 'Les articles et la négation',
          en: 'Articles and negation',
        },
        intro: {
        darija: 'فـ الدارجة ما كنحتاجوش أداة التعريف «ال» بحال العربية. كنقولو **«عندي ولد»** و**«راني فـ الدار»**، و«واش كاين؟» هي السؤال اللي كيستعمل فـ كل بلاصة.',
          ar: 'في الدارجة لا حاجة إلى أداة التعريف «ال». نقول «عندي ولد» و«راني في الدار».',
          fr: "En darija, pas d'article défini. On dit « عندي ولد » (j'ai un fils) et « راني فـ الدار ».",
        },
        sections: [
          {
            type: 'text',
            body: {
              darija: '**واش كاين؟** معناها «هل يوجد؟» وكتجاوب بيها. مثال: **واش كاين شي بن؟** = هل عندك ابن؟\n\n**ما كاينش** = لا يوجد. مثال: **ما كاينش الخدمة** = الخدمة غير ماشي خدّامة.\n\nو**فـ** ولا **ديال** = ديال. **دار محمد** = بيت محمد. **ولد أحمد** = ابن أحمد.',
              ar: '«واش كاين؟» تعني «هل يوجد؟». و«ما كاينش» تعني «لا يوجد». و«فـ» أو «ديال» تعني «خاص/ ديال».',
              fr: "«واش كاين؟ » = est-ce qu'il y a ? · « ما كاينش » = il n'y a pas. · « فـ » / « ديال » = de / à.",
            },
          },
          {
            type: 'text',
            body: {
        darija: '**راني** = أنا. **نتا** = أنت. **هي** = هي.\n\n**عندك** = عندك. مثال: **واش عندك شي أخت؟** = هل عندك أخت؟\n\n**فـ** = فـ / فالـ / تالـ حسب الكلمة اللي بعدها. **فـ الدار** (في الدار)، **فـ الخدمة** (في الخدمة)، **فـ المدرسة** (في المدرسة).',
              ar: '«راني» = أنا. «نتا» = أنت. «عندك» = لديك. «فـ» = في.',
              fr: "« راني » = je suis · « عندك » = tu as · « فـ » = à / dans / au.",
            },
          },
        ],
        examples: [
          {
            source: 'واش عندك شي أخت؟',
            translit: 'wash 3andek chi okht?',
            translation: { darija: 'واش عندك شي أخت؟', ar: 'هل عندك أخت؟', fr: 'Tu as une sœur ?', en: 'Do you have a sister?' },
            audio: 'ar-MA',
          },
          {
        source: 'ما كاينش مشكل، راني فـ الدار.',
            translit: 'ma kaynch mochkil, rani f-dar.',
            translation: { darija: 'ما كاينش مشكل، راني فـ الدار.', ar: 'لا مشكلة، أنا في البيت.', fr: 'Pas de problème, je suis à la maison.', en: 'No problem, I am at home.' },
            audio: 'ar-MA',
          },
          {
            source: 'دار خويا فـ مراكش.',
            translit: 'dar khoya f-Marrakech.',
            translation: { darija: 'دار خويا فـ مراكش.', ar: 'بيت أخي في مراكش.', fr: 'La maison de mon frère est à Marrakech.', en: 'My brother\'s house is in Marrakech.' },
            audio: 'ar-MA',
          },
        ],
        vocab: [
          { word: 'واش كاين؟', translit: 'wash kayn?', audio: 'ar-MA', translation: { ar: 'هل يوجد؟', fr: 'est-ce qu’il y a ?', en: 'is there?' } },
          { word: 'ما كاينش', translit: 'ma kaynch', audio: 'ar-MA', translation: { ar: 'لا يوجد', fr: 'il n’y a pas', en: 'there is no' } },
          { word: 'عندك', translit: '3andek', audio: 'ar-MA', translation: { ar: 'عندك', fr: 'tu as', en: 'you have' } },
          { word: 'راني', translit: 'rani', audio: 'ar-MA', translation: { ar: 'أنا (أنا موجود)', fr: 'je suis', en: 'I am' } },
          { word: 'خويا', translit: 'khoya', audio: 'ar-MA', translation: { ar: 'أخي', fr: 'mon frère', en: 'my brother' } },
          { word: 'أخت', translit: 'okht', audio: 'ar-MA', translation: { ar: 'أخت', fr: 'sœur', en: 'sister' } },
          { word: 'ولد', translit: 'weld', audio: 'ar-MA', translation: { ar: 'ابن / ولد', fr: 'fils', en: 'son' } },
          { word: 'دار', translit: 'dar', audio: 'ar-MA', translation: { ar: 'بيت', fr: 'maison', en: 'house' } },
          { word: 'مراكش', translit: 'Marrakech', audio: 'ar-MA', translation: { ar: 'مراكش', fr: 'Marrakech', en: 'Marrakech' } },
        ],
        exercises: [
          {
            id: 'darija-a1-2-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'شنو كيعني «ما كاينش»؟', fr: 'Que signifie « ما كاينش » ?', en: 'What does "ما كاينش" mean?' },
            options: [
              { text: 'كاين بزاف', audio: 'ar-MA' },
              { text: 'ماكاينش', audio: 'ar-MA' },
              { text: 'واش كاين؟', audio: 'ar-MA' },
              { text: 'بغيت', audio: 'ar-MA' },
            ],
            answer: 1,
            explanation: { darija: '«ما كاينش» = لا يوجد / ماكاينش.', fr: 'Cela signifie « il n’y a pas ».', en: 'It means "there is not".' },
          },
          {
            id: 'darija-a1-2-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'كمّل: واش ______ شي أخت؟', fr: 'Complète : واش ______ شي أخت ؟', en: 'Complete: Do you ______ a sister?' },
            answer: 'عندك',
            accept: ['عندك', '3andek', 'واش عندك'],
            explanation: { darija: 'باش تسول على شي حاجة عندك، كنقولو «واش عندك…؟»', fr: 'Pour demander si tu possèdes quelque chose : « واش عندك…؟ »', en: 'To ask if someone has something, use "واش عندك…؟".' },
          },
          {
            id: 'darija-a1-2-e3',
            type: 'mcq',
            xp: 10,
            prompt: { native: '«راني فـ مراكش» كتعني شنو؟', fr: '«راني فـ مراكش» veut dire quoi ?', en: 'What does "I am in Marrakech" mean in Darija?' },
            options: [
              { text: 'غادي نمشي لمركش', audio: 'ar-MA' },
              { text: 'أنا فـ مراكش دابا', audio: 'ar-MA' },
              { text: 'بغيت نمشي لمركش', audio: 'ar-MA' },
              { text: 'مراكش بعيدة', audio: 'ar-MA' },
            ],
            answer: 1,
            explanation: { darija: '«راني» = أنا (فـ الجواب على «فين نتا؟»).', fr: '« راني » = je suis (en réponse à « où es-tu ? »).', en: '"راني" means "I am / I am located".' },
          },
          {
            id: 'darija-a1-2-e4',
            type: 'translate',
            xp: 10,
            prompt: { fr: 'Tu as un frère ?', en: 'Do you have a brother?' },
            answer: 'واش عندك خويا',
            accept: ['واش عندك خويا', 'واش عندك اخ', 'wash 3andek khoya', 'عندك خويا', 'واش عندك خويا؟'],
            explanation: { darija: 'بالحروف الكبيرة: «واش عندك خويا؟»', fr: 'En majuscules : «واش عندك خويا؟»', en: 'Capitalised: "Do you have a brother?"' },
          },
          {
            id: 'darija-a1-2-e5',
            type: 'listen',
            xp: 15,
            audio: 'ar-MA',
            audioText: 'ما كاينش مشكل',
            prompt: { fr: 'Écoute. Que veut-il dire ?', en: 'Listen. What does it mean?' },
            options: [
              { text: 'Il y a un problème' },
              { text: 'Pas de problème' },
              { text: 'C’est un problème' },
              { text: 'Je ne sais pas' },
            ],
            answer: 1,
            explanation: { darija: '«ما كاينش مشكل» = لا مشكلة / عادي.', fr: '« ما كاينش مشكل » = pas de problème.', en: 'It means "no problem".' },
          },
        ],
      },
      {
        id: 'darija-a1-3',
        order: 3,
        icon: '\u{1F3E0}',
        xp: 50,
        duration: 10,
        title: {
          native: 'فين راك؟ وفين غادي؟',
          darija: 'فين راك؟ بيناتنا',
          ar: 'أين أنت؟ أين نذهب؟',
          fr: 'Où es-tu ? Où va-t-on ?',
          en: 'Where are you? Where to?',
        },
        subtitle: {
          darija: 'السؤال ديال البلاصة والأفعال ديال السير',
          ar: 'المكان والأفعال',
          fr: 'Le lieu et les verbes de mouvement',
          en: 'Places and movement verbs',
        },
        intro: {
        darija: '«فين راك؟» = فين نتا دابا؟ هنا غادي نتعلمو كيفاش كنسولو على البلاصة وكيتجاوب عليها.',
          ar: 'نتعلم السؤال عن المكان والأفعال التي تدل على الذهاب والإياب.',
          fr: "On apprend ici à demander où quelqu'un est et à employer les verbes de mouvement.",
        },
        sections: [
          {
            type: 'text',
            body: {
              darija: '**فين** = فين / في أي بلاصة.\n\n**راك** = أنت (الآن)، مثل «نتا» ولكن فـ الجواب على «فين نتا؟».\n\n**نتا** / **راك** / **راه** (فـ مصر) = أنت.\n\n**فـ الدار**، **فـ الخدمة**، **فـ السوق**، **فـ Schule**، **فـ Hôpital**.',
              ar: '«فين» = أين. «راك» = أنت (الآن). «نتا» = أنت.',
              fr: "« فين » = où · « راك » = tu es (maintenant) · « نتا » = tu.",
            },
          },
          {
            type: 'text',
            body: {
        darija: 'للأفعال ديال السير كاينين: **مشى** (mshi) = يذهب، **جا** (ja) = يجيء، **قعد** (9ed) = يجلس، **طار** (tay) = يطير.\n\nفـ الدارجة، الأفعال كتاخد **ي** ولا ماكتاخدش. **مشى** ولا **يمشي** بجوج صحيح.\n\n**غادي** = غادي / راح. **بغيت** = بغييت / نبغي.',
              ar: 'أفعال الحركة: مشى = يذهب، جا = يأتي، قعد = يجلس. «بغيت» = أريد، «غادي» = سأذهب.',
              fr: "Verbes : مشى (aller) · جا (venir) · قعد (s'asseoir). « بغيت » = je veux · « غادي » = je vais.",
            },
          },
        ],
        examples: [
          {
            source: 'فين راك؟ — راني فـ المدرسة.',
            translit: 'fin rak? — rani f-l-madrasa.',
            translation: { darija: 'فين راك؟ — راني فـ المدرسة.', ar: 'أين أنت؟ — أنا في المدرسة.', fr: 'Où es-tu ? — Je suis à l’école.', en: 'Where are you? — I am at school.' },
            audio: 'ar-MA',
          },
          {
            source: 'واش غادي تهضر معايا؟',
            translit: 'wash ghadi thder m3aya?',
            translation: { darija: 'واش غادي تهضر معايا؟', ar: 'هل ستتحدث معي؟', fr: 'Tu vas parler avec moi ?', en: 'Will you speak with me?' },
            audio: 'ar-MA',
          },
          {
            source: 'راه جاي فـ الطريق.',
            translit: 'rah ja f-tari9.',
            translation: { darija: 'راه جاي فـ الطريق.', ar: 'هو في الطريق.', fr: 'Il est en route.', en: 'He is on the way.' },
            audio: 'ar-MA',
          },
        ],
        vocab: [
          { word: 'فين', translit: 'fin', audio: 'ar-MA', translation: { ar: 'أين', fr: 'où', en: 'where' } },
          { word: 'راك', translit: 'rak', audio: 'ar-MA', translation: { ar: 'أنت (الآن)', fr: 'tu es', en: 'you are' } },
          { word: 'غادي', translit: 'ghadi', audio: 'ar-MA', translation: { ar: 'سـ / راح', fr: 'je vais', en: 'I will' } },
          { word: 'مشى', translit: 'mshi', audio: 'ar-MA', translation: { ar: 'ذهب', fr: 'aller', en: 'to go' } },
          { word: 'جا', translit: 'ja', audio: 'ar-MA', translation: { ar: 'جاء', fr: 'venir', en: 'to come' } },
          { word: 'قعد', translit: '9ed', audio: 'ar-MA', translation: { ar: 'جلس', fr: 's’asseoir', en: 'to sit' } },
          { word: 'معا', translit: 'm3a', audio: 'ar-MA', translation: { ar: 'مع', fr: 'avec', en: 'with' } },
          { word: 'الطريق', translit: 'tari9', audio: 'ar-MA', translation: { ar: 'الطريق', fr: 'la route', en: 'the road' } },
        ],
        exercises: [
          {
            id: 'darija-a1-3-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'واش كيعني «غادي»؟', fr: 'Que signifie « غادي » ?', en: 'What does "غادي" mean?' },
            options: [
              { text: 'رحت', audio: 'ar-MA' },
              { text: 'غادي / راح / باش يمشي', audio: 'ar-MA' },
              { text: 'ماشي عجبني', audio: 'ar-MA' },
              { text: 'كتسنى', audio: 'ar-MA' },
            ],
            answer: 1,
            explanation: { darija: '«غادي» = راح / باش يمشي (المستقبل القريب).', fr: '« غادي » = je vais / tu vas.', en: 'It means "I will / you will go".' },
          },
          {
            id: 'darija-a1-3-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'كمّل: ______ راك؟ — راني فـ الخدمة.', fr: 'Complète : ______ راك ? — راني فـ الخدمة.', en: 'Complete: Where are you?' },
            answer: 'فين',
            accept: ['فين', 'fin'],
            explanation: { darija: '«فين راك؟» = فين نتا الآن؟', fr: '« فين راك ؟ » = où es-tu ?', en: '"فين راك؟" means "where are you?".' },
          },
          {
            id: 'darija-a1-3-e3',
            type: 'translate',
            xp: 10,
            prompt: { fr: 'Je vais au marché.', en: 'I am going to the market.' },
            answer: 'غادي نمشي فـ السوق',
            accept: ['غادي نمشي فـ السوق', 'راح نمشي فـ السوق', 'ghadi nmshi f-sou9', 'غادي نمشي للسوق', 'نمشي فـ السوق'],
    explanation: { darija: '«السوق» كتعني السوق ديال الخضر والفواكه.', fr: '« السوق » = le marché.', en: 'Souk means market.' },
          },
          {
            id: 'darija-a1-3-e4',
            type: 'mcq',
            xp: 10,
            prompt: { native: '«معا» كتعني شنو؟', fr: 'Que signifie « معا » ?', en: 'What does "معا" mean?' },
            options: [
              { text: 'de / ديال', audio: 'ar-MA' },
              { text: 'مع / avec', audio: 'ar-MA' },
              { text: 'بلا / sans', audio: 'ar-MA' },
              { text: 'قريب / près', audio: 'ar-MA' },
            ],
            answer: 1,
            explanation: { darija: '«معا» = مع. «بلا» = بلا / بدون.', fr: '« معا » = avec. « بلا » = sans.', en: '"معا" = with, "بلا" = without.' },
          },
          {
            id: 'darija-a1-3-e5',
            type: 'speak',
            xp: 20,
            audio: 'ar-MA',
            audioText: 'فين راك؟ راني فـ الخدمة.',
            prompt: { fr: 'Dis : « Où es-tu ? — Je suis au travail. »', en: 'Say: "Where are you?" — "I am at work."' },
            explanation: { darija: 'جرّب تسمع صوتك وتصحّحو.', fr: 'Écoute-toi et corrige.', en: 'Listen to yourself and correct.' },
          },
        ],
      },
    ],
  },
  {
    level: 'A2',
    lessons: [
      {
        id: 'darija-a2-1',
        order: 1,
        icon: '\u{1F6D2}',
        xp: 70,
        duration: 12,
        title: {
        native: 'فـ السوق — الألوان والأرقام',
          darija: 'فـ السوق: الألوان والأرقام',
          ar: 'في السوق: الألوان والأرقام',
          fr: 'Au marché : couleurs et nombres',
          en: 'At the market: colours and numbers',
        },
        subtitle: {
          darija: 'الشراء، الثمن، والمصالحة',
          ar: 'الشراء والثمن',
          fr: 'Acheter, les prix, négocier',
          en: 'Buying, prices, haggling',
        },
        intro: {
          darija: 'فـ السوق ديال مراكش ولا كازا، كل شي كتفاوض عليه. خاصك تعرف الأرقام بالعربية والألوان باش ما تغلي عليك.',
          ar: 'في السوق، كل شيء يُساوم عليه. من المهم معرفة الأرقام والألوان.',
          fr: "Au marché, tout se négocie. Il faut connaître les chiffres et les couleurs.",
        },
        sections: [
          {
            type: 'text',
            body: {
        darija: '**الأرقام:**\nواحد 1 · اثنين 2 · تلاتة 3 · أربعة 4 · خمسة 5 · ستة 6 · سبعة 7 · ثمانية 8 · تسعة 9 · عشرة 10.\n\n**التسعير:** **بشحال؟** = شحال ثمن هاد الشي؟ **غالي بزاف!** = غالي بزاف.\n\n**التفاوض:** **نقص لي** = نقص لي الثمن شوية. **مليح!** = حاضر / مزيان.',
              ar: 'الأرقام: 1 واحد ... 10 عشرة. «بشحال؟» = كم الثمن؟ «نقص لي» = اخفض لي.',
              fr: "Chiffres : 1 واحد … 10 عشرة. « بشحال ؟ » = combien ? « نقص لي » = faites un prix.",
            },
          },
          {
            type: 'text',
            body: {
        darija: '**الألوان:** أحمر، أزرق، أخضر، أصفر، أبيض، أسود، رمادي، برتقالي، بنفسجي.\n\n**الحجم:** صغير، كبير، وسط.\n\n**السؤال:** **عطيني** = عطيني. **واش عندك؟** = واش عندك هاد الشي؟',
              ar: 'الألوان: أحمر، أزرق، أخضر، أصفر، أبيض، أسود. «عطيني» = أعطني.',
              fr: "Couleurs : rouge, bleu, vert, jaune, blanc, noir. « عطيني » = donnez-moi.",
            },
          },
        ],
        examples: [
          {
            source: 'بشحال هاد البرتقال؟',
            translit: 'bch7al had l-bortuqal?',
            translation: { darija: 'بشحال هاد البرتقال؟', ar: 'كم ثمن هذا البرتقال؟', fr: 'C’est combien, ces oranges ?', en: 'How much are these oranges?' },
            audio: 'ar-MA',
          },
          {
            source: 'غالي بزاف! نقص لي شوية.',
            translit: 'ghali bzaf! n9es li chwiya.',
            translation: { darija: 'غالي بزاف! نقص لي شوية.', ar: 'غالي جداً! اخفض لي قليلاً.', fr: 'C’est trop cher ! Faites un prix.', en: 'Too expensive! Lower the price a bit.' },
            audio: 'ar-MA',
          },
          {
            source: 'واش عندك شي فواكه حمرا؟',
            translit: 'wash 3andek chi fwi7a 7amra?',
            translation: { darija: 'واش عندك شي فواكه حمرا؟', ar: 'هل عندك فواكه حمراء؟', fr: 'Tu as des fruits rouges ?', en: 'Do you have red fruit?' },
            audio: 'ar-MA',
          },
        ],
        vocab: [
          { word: 'بشحال؟', translit: 'bch7al?', audio: 'ar-MA', translation: { ar: 'كم؟', fr: 'combien ?', en: 'how much?' } },
          { word: 'غالي', translit: 'ghali', audio: 'ar-MA', translation: { ar: 'غالي', fr: 'cher', en: 'expensive' } },
          { word: 'رخيص', translit: 'rkhis', audio: 'ar-MA', translation: { ar: 'رخيص', fr: 'bon marché', en: 'cheap' } },
          { word: 'نقص لي', translit: 'n9es li', audio: 'ar-MA', translation: { ar: 'اخفض لي', fr: 'faisez un prix', en: 'lower it' } },
          { word: 'عطيني', translit: '3tini', audio: 'ar-MA', translation: { ar: 'أعطني', fr: 'donne-moi', en: 'give me' } },
          { word: 'أخضر', translit: 'akhdar', audio: 'ar-MA', translation: { ar: 'أخضر', fr: 'vert', en: 'green' } },
          { word: 'أصفر', translit: 'asfar', audio: 'ar-MA', translation: { ar: 'أصفر', fr: 'jaune', en: 'yellow' } },
          { word: 'السوق', translit: 'sou9', audio: 'ar-MA', translation: { ar: 'السوق', fr: 'le marché', en: 'market' } },
        ],
        exercises: [
          {
            id: 'darija-a2-1-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'واش كينفع «بشحال هاد القميص؟»', fr: 'Comment demander le prix d’une chemise ?', en: 'How do you ask the price of a shirt?' },
            options: [
              { text: 'واش كاين القميص؟', audio: 'ar-MA' },
              { text: 'بشحال هاد القميص؟', audio: 'ar-MA' },
              { text: 'فين هو القميص؟', audio: 'ar-MA' },
              { text: 'واش بغيتي القميص؟', audio: 'ar-MA' },
            ],
            answer: 1,
            explanation: { darija: '«بشحال» = كم (الثمن).', fr: '« بشحال » = combien (le prix).', en: '"بشحال" asks for the price.' },
          },
          {
            id: 'darija-a2-1-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'كمّل: ______ بزاف! — طيب، ______ لي شوية.', fr: 'Complète : ______ بزاف ! — طيب، ______ لي شوية.', en: 'Complete: too expensive — lower the price.' },
            answer: 'غالي',
            accept: ['غالي', 'ghali', 'غالي بزاف'],
            explanation: { darija: '«غالي» = cher. «نقص لي» = faites un prix.', fr: '« غالي » = cher. « نقص لي » = faites un prix.', en: '"غالي" = expensive, "نقص لي" = lower it.' },
          },
          {
            id: 'darija-a2-1-e3',
            type: 'translate',
            xp: 10,
            prompt: { fr: 'Donnez-moi deux kilos de tomates.', en: 'Give me two kilos of tomatoes.' },
            answer: 'عطيني كيلو و زدوج من الطماطم',
            accept: ['عطيني كيلو و زدوج من الطماطم', 'عطيني kilo w zedouz dyal ttmatem', 'kilo w zedouz', 'kilo w zouj', 'كيلو و زوج من الطماطم', 'عطيني كيلوج و زوج'],
            hint: 'فكّر فـ «كيلو و زدوج»',
            explanation: { darija: '«و زدوج» = اثنين. كيقولو «كيلو و زدوج» = 2 كيلو.', fr: '« و زدوج » = deux.', en: '"و زدوج" means two.' },
          },
          {
            id: 'darija-a2-1-e4',
            type: 'listen',
            xp: 15,
            audio: 'ar-MA',
            audioText: 'خمسة و أربعين درهم',
            prompt: { fr: 'Écoute le prix. Combien ?', en: 'Listen to the price. How much?' },
            options: [
              { text: '45 dirhams' },
              { text: '25 dirhams' },
              { text: '40 dirhams' },
              { text: '15 dirhams' },
            ],
            answer: 0,
            explanation: { darija: 'خمسين (40) و خمسة (5) = 45 درهم.', fr: '40 + 5 = 45 dirhams.', en: '40 + 5 = 45 dirhams.' },
          },
        ],
      },
      {
        id: 'darija-a2-2',
        order: 2,
        icon: '\u{1F5E3}\u{FE0F}',
        xp: 70,
        duration: 11,
        title: {
        native: 'الزيارات والإشارات',
        darija: 'الزيارات والإشارات',
          ar: 'الزيارات والإشارات',
          fr: 'Visites et indications',
          en: 'Visits and directions',
        },
        subtitle: {
          darija: 'كيفاش تسأل على الطريق فـمراكش ولا فـالدار البيضاء',
          ar: 'كيف تسأل عن الطريق',
          fr: 'Demander son chemin',
          en: 'Asking for directions',
        },
        intro: {
          darija: 'فـ أي مدينة مغربية، كول واحد كيرشدك. السؤال ديال الطريق هو: **«واش كاين الطريق لـ…؟»**',
          ar: 'في كل مدينة مغربية، الناس يرشدونك. السؤال: «واش كاين الطريق لـ…؟»',
          fr: "Dans n'importe quelle ville marocaine, on vous guidera. On demande : « واش كاين الطريق لـ…؟ »",
        },
        sections: [
          {
            type: 'text',
            body: {
        darija: '**واش كاين الطريق لفين؟** = كيفاش نمشي لفيـن؟\n\n**على اليمين** = على اليمين. **على اليسار** = على اليسار. **القدام** = إلى الأمام. **ورا** = إلى الخلف.\n\n**دور على اليمين** = انعطف يميناً. **كمّل قدّام** = واصل إلى الأمام. **كول فـ** = ادخل.',
              ar: '«على اليمين» = يميناً. «القدام» = أماماً. «دور» = انعطف. «كمّل قدّام» = تابع.',
              fr: "« على اليمين » = à droite · « القدام » = tout droit · « دور » = tourne · « كمّل قدّام » = continue tout droit.",
            },
          },
          {
            type: 'text',
            body: {
        darija: '**المعالم:**\n\n**جامع** = مسجد. **مكتبة** = مكتبة. **متحف** = متحف. **ساحة** = ساحة. **دار** = بيت/قصر. **جامع الفنا** = ساحة جامع الفنا فـ مراكش.',
              ar: 'جامع = مسجد، مكتبة = مكتبة، متحف = متحف، ساحة = ساحة.',
              fr: "جامع = mosquée · مكتبة = bibliothèque · متحف = musée · ساحة = place.",
            },
          },
        ],
        examples: [
          {
            source: 'واش كاين الطريق لجامع الفنا؟',
            translit: 'wash kayen t-tri9 l-jami3 l-fana?',
            translation: { darija: 'واش كاين الطريق لجامع الفنا؟', ar: 'هل الطريق إلى جامع الفنا؟', fr: 'C’est par là la mosquée Jemaa el-Fna ?', en: 'Is the road to Jemaa el-Fna this way?' },
            audio: 'ar-MA',
          },
          {
            source: 'دور على اليمين و كمّل قدّام.',
            translit: 'ddour 3la l-yamin o kammel 9ddam.',
            translation: { darija: 'دور على اليمين و كمّل قدّام.', ar: 'انعطف يميناً وامشِ أماماً.', fr: 'Tourne à droite et continue tout droit.', en: 'Turn right and keep going straight.' },
            audio: 'ar-MA',
          },
          {
            source: 'غادي تقبض على ليمن راسك.',
            translit: 'ghadi teqbed 3la l-yamin rasek.',
            translation: { darija: 'غادي تقبض على ليمن راسك.', ar: 'ستكون على يمينك.', fr: 'Ce sera sur votre droite.', en: 'It will be on your right.' },
            audio: 'ar-MA',
          },
        ],
        vocab: [
          { word: 'الطريق', translit: 'tri9', audio: 'ar-MA', translation: { ar: 'الطريق', fr: 'la route / chemin', en: 'road' } },
          { word: 'يمين', translit: 'yamin', audio: 'ar-MA', translation: { ar: 'يمين', fr: 'droite', en: 'right' } },
          { word: 'يسار', translit: 'yser', audio: 'ar-MA', translation: { ar: 'يسار', fr: 'gauche', en: 'left' } },
          { word: 'قدّام', translit: '9ddam', audio: 'ar-MA', translation: { ar: 'أمام', fr: 'devant / tout droit', en: 'ahead' } },
          { word: 'ورا', translit: 'wra', audio: 'ar-MA', translation: { ar: 'خلف', fr: 'derrière', en: 'behind' } },
          { word: 'جامع', translit: 'jami3', audio: 'ar-MA', translation: { ar: 'مسجد', fr: 'mosquée', en: 'mosque' } },
          { word: 'متحف', translit: 'mathaf', audio: 'ar-MA', translation: { ar: 'متحف', fr: 'musée', en: 'museum' } },
          { word: 'قريب', translit: '9rib', audio: 'ar-MA', translation: { ar: 'قريب', fr: 'près', en: 'near' } },
        ],
        exercises: [
          {
            id: 'darija-a2-2-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'واحد قال ليك «دور على اليسار». شنو كتدير؟', fr: 'Quelqu’un te dit « tourne à gauche ». Tu fais quoi ?', en: 'Someone says "turn left". What do you do?' },
            options: [
              { text: 'كتمشي على اليمين', audio: 'ar-MA' },
              { text: 'كتدور على اليسار', audio: 'ar-MA' },
              { text: 'كتوقف', audio: 'ar-MA' },
              { text: 'كتسنى شي حد آخر', audio: 'ar-MA' },
            ],
            answer: 1,
            explanation: { darija: '«دور» = انعطف. «على اليسار» = على اليسار.', fr: '« دور » = tourne. « على اليسار » = à gauche.', en: '"دور" = turn, "على اليسار" = to the left.' },
          },
          {
            id: 'darija-a2-2-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'كمّل: غادي تلقاه على ______ راسك.', fr: 'Complète : غادي تلقاه على ______ راسك.', en: 'Complete: You will find it on your ...' },
            answer: 'اليمين',
            accept: ['اليمين', 'yamin', 'ليمن', 'يمين'],
            explanation: { darija: '«على اليمين راسك» = على يمينك. «على اليسار راسك» = على يسارك.', fr: '« sur votre droite » / « sur votre gauche ».', en: 'On your right / on your left.' },
          },
          {
            id: 'darija-a2-2-e3',
            type: 'translate',
            xp: 10,
            prompt: { fr: 'Comment je vais au marché ?', en: 'How do I get to the market?' },
            answer: 'واش كاين الطريق للسوق',
            accept: ['واش كاين الطريق للسوق', 'واش كاين الطريق ل السوق', 'wash kayen t-tri9 l-sou9', 'كيفاش نمشي للسوق', 'فين السوق'],
            explanation: { darija: 'الطريقة الطبيعية: «واش كاين الطريق لـ[الهدف]؟»', fr: 'La formule naturelle : « واش كاين الطريق لـ…؟ »', en: 'The natural phrase: "واش كayn t-tri9 l…?"' },
          },
          {
            id: 'darija-a2-2-e4',
            type: 'speak',
            xp: 20,
            audio: 'ar-MA',
            audioText: 'واش كاين الطريق للبيت؟',
            prompt: { fr: 'Dis : « Où est le chemin ? » puis demande ton chemin.', en: 'Say: "Where is the road?" then ask for directions.' },
            explanation: { darija: 'تدرّب مع شي حد. «واش كاين الطريق ل…؟»', fr: 'Entraîne-toi : « واش كاين الطريق لـ…؟ »', en: 'Practise: "واش كayn t-tri9 l…?"' },
          },
        ],
      },
    ],
  },
]
