export const englishLessons = [
  {
    level: 'A1',
    lessons: [
      {
        id: 'en-a1-1',
        order: 1,
        icon: '\u{1F44B}',
        xp: 50,
        duration: 8,
        title: {
          native: 'Hello, my name is',
          darija: 'السلام عليكم، سمّيتي',
          ar: 'مرحبًا، اسمي',
          fr: 'Bonjour, je m’appelle',
          en: 'Hello, my name is',
        },
        subtitle: {
          darija: 'الضمائر وأفعال الـ be',
          ar: 'الضمائر وأفعال be',
          fr: 'Pronoms et verbe be',
          en: 'Pronouns and the verb be',
        },
        intro: {
          darija: 'فـ الإنجليزية كاين **a / an** قبل الكلمة، و**am / is / are** مع الضمائر. خاصك تحفظهم كزوج.',
          ar: 'في الإنجليزية تسبق الكلمة أداة a أو an، والفعل be يتغير حسب الضمير.',
          fr: 'En anglais, on utilise a / an devant un nom, et le verbe be change avec le pronom.',
        },
        sections: [
          {
            type: 'text',
            body: {
              en: '**I am** from Morocco. **You are** welcome. **He is** my brother. **She is** my sister. **We are** friends. **They are** from Spain.\n\n**Full form** = I am / You are… but in speech we say **I’m**, **you’re**, **he’s**, **she’s**, **we’re**, **they’re**.',
              darija: '**I am** = أنا، **You are** = نتا/نتي، **He is** = هو، **She is** = هي، **We are** = حنا، **They are** = هوما.\n\nالطريقة الكاملة: I am، You are… ولكن فـ الكلام كنقصرو: I’m، you’re، he’s…',
              ar: 'I am = أنا، You are = أنت، He/She is = هو/هي، We are = نحن، They are = هم.',
              fr: 'I am = je suis, You are = tu es, He/She is = il/elle est, We are = nous sommes.',
            },
          },
          {
            type: 'text',
            body: {
              en: '**a** before a consonant sound (a book, a car)\n**an** before a vowel sound (an apple, an hour — the H is silent)\n\n**My / your / his / her / our / their** = possessives. Never use ’s for people: say **my brother**, not *my brother’s* (that means "of my brother").',
              darija: '**a** قبل الصوت الساكن (a book)، و**an** قبل الصوت المتحرك (an apple). و**s** ما كتجيبش مع الناس: كنقولو **my brother** ماشي *my brother’s*.',
              ar: 'a قبل صوت الساكن و an قبل صوت المتحرك. مع الناس استعمل my brother لا my brother’s.',
              fr: 'a avant une consonne, an avant une voyelle. my / your / his / her pour la possession.',
            },
          },
        ],
        examples: [
          {
            source: "Hi, I'm Youssef. I'm from Rabat.",
            translation: { darija: 'السلام عليكم، أنا يوسف. جيت من الرباط.', ar: 'مرحبًا، أنا يوسف. من الرباط.', fr: 'Salut, je suis Youssef. Je viens de Rabat.', en: 'Hi, I am Youssef. I am from Rabat.' },
            audio: 'en-US',
          },
          {
            source: "She's a nurse, he's a teacher.",
            translation: { darija: 'هي ممرضة، هو أستاذ.', ar: 'هي ممرضة، هو معلم.', fr: 'Elle est infirmière, il est professeur.', en: 'She is a nurse, he is a teacher.' },
            audio: 'en-US',
          },
          {
            source: "We are Moroccan, they are Spanish.",
            translation: { darija: 'حنا مغاربة، هوما إسبان.', ar: 'نحن مغاربة، هم إسبان.', fr: 'Nous sommes marocains, ils sont espagnols.', en: 'We are Moroccan, they are Spanish.' },
            audio: 'en-US',
          },
        ],
        vocab: [
          { word: 'hello', audio: 'en-US', translation: { darija: 'السلام عليكم', ar: 'مرحبًا', fr: 'bonjour', en: 'hello' } },
          { word: 'name', audio: 'en-US', translation: { darija: 'الاسم', ar: 'الاسم', fr: 'nom', en: 'name' } },
          { word: 'from', audio: 'en-US', translation: { darija: 'من', ar: 'من', fr: 'de', en: 'from' } },
          { word: 'friend', audio: 'en-US', translation: { darija: 'صاحب / صاحبة', ar: 'صديق', fr: 'ami', en: 'friend' } },
          { word: 'brother', audio: 'en-US', translation: { darija: 'خويا', ar: 'أخ', fr: 'frère', en: 'brother' } },
          { word: 'sister', audio: 'en-US', translation: { darija: 'أخت', ar: 'أخت', fr: 'sœur', en: 'sister' } },
          { word: 'teacher', audio: 'en-US', translation: { darija: 'أستاذ', ar: 'معلم', fr: 'professeur', en: 'teacher' } },
          { word: 'thank you', audio: 'en-US', translation: { darija: 'شكراً', ar: 'شكرًا', fr: 'merci', en: 'thank you' } },
        ],
        exercises: [
          {
            id: 'en-a1-1-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'I ___ from Morocco.', fr: 'I ___ from Morocco.', en: 'I am from Morocco.' },
            options: [
              { text: 'am' },
              { text: 'is' },
              { text: 'are' },
              { text: 'be' },
            ],
            answer: 0,
            explanation: { darija: 'مع I كنسميو am. مع he/she كنسميو is. مع we/they كنسميو are.', fr: 'Avec I : am. Avec he/she : is. Avec we/they : are.', en: 'I take am, he/she takes is, we/they take are.' },
          },
          {
            id: 'en-a1-1-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'She ___ my sister.', fr: 'She ___ my sister.', en: 'She is my sister.' },
            answer: 'is',
            accept: ['is', '’s', "'s"],
            explanation: { darija: 'She is = هي كيكون/تكون.', fr: 'She is = elle est.', en: '"She is" means "she is".' },
          },
          {
            id: 'en-a1-1-e3',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'I have ___ apple.', fr: 'J’ai ___ pomme.', en: 'I have an apple.' },
            options: [
              { text: 'a' },
              { text: 'an' },
              { text: 'the' },
              { text: 'one' },
            ],
            answer: 1,
            explanation: { darija: 'apple كتبدا بصوت متحرك، إذن an.', fr: 'apple commence par une voyelle : an.', en: 'apple starts with a vowel sound, so "an".' },
          },
          {
            id: 'en-a1-1-e4',
            type: 'translate',
            xp: 10,
            prompt: { en: 'I am Moroccan.', fr: 'Je suis marocain.' },
            answer: 'i am moroccan',
            accept: ['i am moroccan', 'im moroccan', 'i\'m moroccan', 'i am marocain'],
            explanation: { darija: '«Moroccan» = مغربي. كنعطيها بلا أداة التعريف.', fr: '« Moroccan » sans article.', en: 'No article is used with nationalities here.' },
          },
          {
            id: 'en-a1-1-e5',
            type: 'listen',
            xp: 15,
            audio: 'en-US',
            audioText: 'She is a nurse.',
            prompt: { fr: 'Listen. What is she?', en: 'Listen. What is she?' },
            options: [
              { text: 'A teacher' },
              { text: 'A nurse' },
              { text: 'A doctor' },
              { text: 'A student' },
            ],
            answer: 1,
            explanation: { darija: 'a nurse = ممرضة.', fr: 'a nurse = une infirmière.', en: '"nurse" means infirmière / ممرضة.' },
          },
          {
            id: 'en-a1-1-e6',
            type: 'speak',
            xp: 20,
            audio: 'en-US',
            audioText: "Hello, my name is Youssef and I'm from Morocco.",
            prompt: { fr: 'Say : « Hello, my name is Youssef and I am from Morocco. »', en: 'Say: "Hello, my name is Youssef and I am from Morocco."' },
            explanation: { darija: 'انتبه للـ th فـ the و the.', fr: 'Attention au th de the.', en: 'Mind the "th" in "the".' },
          },
        ],
      },
      {
        id: 'en-a1-2',
        order: 2,
        icon: '\u{1F6CD}',
        xp: 50,
        duration: 9,
        title: {
          native: 'Every day: present simple',
          darija: 'كل نهار: المضارع البسيط',
          ar: 'المضارع البسيط',
          fr: 'Le présent simple',
          en: 'Present simple',
        },
        subtitle: {
          darija: 'الأفعال العادية والأفعال مع ing',
          ar: 'الأفعال العادية وبدون ing',
          fr: 'Verbes réguliers et en ing',
          en: 'Regular verbs and the -ing form',
        },
        intro: {
          darija: 'فـ الإنجليزية كاين جوجDwimdiوب. القاعدة كات/formule: فـ **he / she / it** زيد **-s** فـ الآخر. بإلا كان الفعل كيسالي بـ s، زيد **-es**.',
          ar: 'في المضارع البسيط نضيف s مع he/she/it، و es إذا كان الفعل ينتهي بـ s.',
          fr: 'Au présent simple, on ajoute s à la 3e personne du singulier.',
        },
        sections: [
          {
            type: 'text',
            body: {
              en: 'I **work**. You **work**. He **works**. She **works**.\nWe **live**. They **live**.\nHe **watch**es TV. She **go**es home.\n\n**Negative:** I **don’t** work. He **doesn’t** work.\n**Question:** **Do** you work? **Does** he work?',
              darija: 'I work = كنخدم، He works = كيخدم.\n\n**النفي:** I don’t work = ما كنخدمش.\n**السؤال:** Do you work؟ = واش كتخدم؟ / Does he work؟',
              ar: 'النفي بـ don’t و doesn’t، والسؤال بـ Do و Does.',
              fr: 'Négatif : don’t / doesn’t. Question : Do…? / Does…?',
            },
          },
          {
            type: 'text',
            body: {
              en: '**Spelling rule:** if the verb ends in a consonant + **y**, change y → **i** before -es.\n\n* study → studies · cry → cries · carry → carries\n\n**Irrregulars to learn first:** go → goes, have → has, do → does, say → says, make → makes.',
              darija: '**القاعدة:** إلا كان الفعل كيسالي بـ **y**، بدلها بـ **i** قبل ما تزيد es. مثال: study → studies.\n\n**أفعال خاصة:** go → goes، have → has، do → does.',
              ar: 'إذا انتهى الفعل بحرف ساكن متبوع بـ y نحوّلها إلى i ثم نضيف es.',
              fr: 'verbe en consonne + y → on change y en i avant -es.',
            },
          },
        ],
        examples: [
          {
            source: 'I work in a restaurant in Lyon.',
            translation: { darija: 'كنخدم فـ مطعم فـ ليون.', ar: 'أعمل في مطعم في ليون.', fr: 'Je travaille dans un restaurant à Lyon.', en: 'I work in a restaurant in Lyon.' },
            audio: 'en-US',
          },
          {
            source: 'She studies medicine.',
            translation: { darija: 'هي كتدرس الطب.', ar: 'هي تدرس الطب.', fr: 'Elle étudie la médecine.', en: 'She studies medicine.' },
            audio: 'en-US',
          },
          {
            source: "Do you speak Arabic?",
            translation: { darija: 'واش كتتكلم العربية؟', ar: 'هل تتحدث العربية؟', fr: 'Tu parles arabe ?', en: 'Do you speak Arabic?' },
            audio: 'en-US',
          },
        ],
        vocab: [
          { word: 'work', audio: 'en-US', translation: { darija: 'يخدم', ar: 'يعمل', fr: 'travailler', en: 'to work' } },
          { word: 'live', audio: 'en-US', translation: { darija: 'ساكن', ar: 'يعيش', fr: 'habiter', en: 'to live' } },
          { word: 'study', audio: 'en-US', translation: { darija: 'يتعلم', ar: 'يدرس', fr: 'étudier', en: 'to study' } },
          { word: 'speak', audio: 'en-US', translation: { darija: 'يتكلم', ar: 'يتحدث', fr: 'parler', en: 'to speak' } },
          { word: 'every day', audio: 'en-US', translation: { darija: 'كل نهار', ar: 'كل يوم', fr: 'tous les jours', en: 'every day' } },
          { word: 'today', audio: 'en-US', translation: { dareja: '', darija: 'اليوم', ar: 'اليوم', fr: 'aujourd’hui', en: 'today' } },
          { word: 'weekend', audio: 'en-US', translation: { darija: 'عطلة نهاية الأسبوع', ar: 'عطلة نهاية الأسبوع', fr: 'le week-end', en: 'weekend' } },
          { word: 'usually', audio: 'en-US', translation: { darija: 'عادة', ar: 'عادة', fr: 'd’habitude', en: 'usually' } },
        ],
        exercises: [
          {
            id: 'en-a1-2-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'He ___ to school every day.', fr: 'He ___ to school every day.', en: 'He goes to school every day.' },
            options: [
              { text: 'go' },
              { text: 'goes' },
              { text: 'going' },
              { text: 'gone' },
            ],
            answer: 1,
            explanation: { darija: 'مع he كيزيد s: go → goes.', fr: 'Avec he : go → goes.', en: 'With he/she/it add -s: go → goes.' },
          },
          {
            id: 'en-a1-2-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'She ___ medicine.', fr: 'She ___ medicine.', en: 'She studies medicine.' },
            answer: 'studies',
            accept: ['studies', 'studys', 'studys'],
            explanation: { darija: 'study + es = studies (y تولي i).', fr: 'study + es = studies (y devient i).', en: 'study + es = studies (y becomes i).' },
          },
          {
            id: 'en-a1-2-e3',
            type: 'translate',
            xp: 10,
            prompt: { en: 'Do you speak Arabic?', fr: 'Tu parles arabe ?' },
            answer: 'do you speak arabic',
            accept: ['do you speak arabic', 'you speak arabic', 'do u speak arabic'],
            explanation: { darija: 'السؤال كيبدا بـ do. إلا كان he/she كيبدا بـ does.', fr: 'La question commence par do (ou does).', en: 'Questions start with do; with he/she use does.' },
          },
          {
            id: 'en-a1-2-e4',
            type: 'mcq',
            xp: 10,
            prompt: { native: "I ___ live in Paris.", fr: 'I ___ live in Paris.', en: 'I do not live in Paris.' },
            options: [
              { text: 'am not' },
              { text: "don't" },
              { text: "doesn't" },
              { text: 'not' },
            ],
            answer: 1,
            explanation: { darija: 'النفي مع I هو don’t. مع he/she هو doesn’t.', fr: 'Négatif : I don’t, he doesn’t.', en: 'Negatives: I don’t, he doesn’t.' },
          },
          {
            id: 'en-a1-2-e5',
            type: 'listen',
            xp: 15,
            audio: 'en-US',
            audioText: 'We usually work on Fridays.',
            prompt: { fr: 'Listen. When do they work?', en: 'Listen. When do they work?' },
            options: [
              { text: 'On Mondays' },
              { text: 'On Fridays' },
              { text: 'On Sundays' },
              { text: 'Never' },
            ],
            answer: 1,
            explanation: { darija: 'Fridays = الجمعة.', fr: 'Friday = vendredi.', en: 'Friday is vendredi / الجمعة.' },
          },
        ],
      },
      {
        id: 'en-a1-3',
        order: 3,
        icon: '\u{1F9D0}',
        xp: 50,
        duration: 9,
        title: {
          native: 'Asking for things',
          darija: 'كيفاش تسول على حاجة',
          ar: 'طلب الأشياء',
          fr: 'Demander des choses',
          en: 'Asking for things',
        },
        subtitle: {
          darija: 'can / could، و How much',
          ar: 'can و could',
          fr: 'can, could et how much',
          en: 'can, could and how much',
        },
        intro: {
          darija: 'فـ الإنجليزية كنطلبو بـ **Can I…؟** و **Could I…؟** (أدب أكثر). و **How much** = بشحال؟',
          ar: 'نطلب المساعدة بـ can و could، ونسأل عن السعر بـ how much.',
          fr: 'On demande avec can / could, et le prix avec how much.',
        },
        sections: [
          {
            type: 'text',
            body: {
              en: '**Can I help you?** = Can I help you?\n**Could you help me, please?** = a request, more polite\n**Sorry, I don’t understand.**\n\n**How much is it?** (price of one thing)\n**How many are there?** (countable things)\n\n**Could I have the bill, please?**',
              darija: '**Can I help you** = واش نقدر نعاونك؟\n**Could you help me please** = واش تقدر تعاوني من فضلك (أدب أكثر).\n**Sorry, I don’t understand** = سمح لي، ما فهمتش.\n\n**How much is it** = بشحال؟ (الثمن)\n**How many are there** = شحال كاين؟ (العدد)',
              ar: 'يمكنني مساعدتك؟ من فضلك ساعدني. آسف لم أفهم. بكم هذا؟ كم عددهم؟',
              fr: 'Puis-je vous aider ? Pouvez-vous m’aider, s’il vous plaît ? Combien ça coûte ?',
            },
          },
        ],
        examples: [
          {
            source: 'How much is this jacket?',
            translation: { darija: 'بشحال هاد الجاكيت؟', ar: 'كم ثمن هذا السترة؟', fr: 'Combien coûte cette veste ?', en: 'How much is this jacket?' },
            audio: 'en-US',
          },
          {
            source: 'Could I have the bill, please?',
            translation: { darija: 'واش تقدر تجيب لي الحساب من فضلك؟', ar: 'من فضلك أحضر الفاتورة.', fr: 'L’addition, s’il vous plaît ?', en: 'Could I have the bill, please?' },
            audio: 'en-US',
          },
          {
            source: "Sorry, I don't understand. Can you repeat, please?",
            translation: { darija: 'سمح لي، ما فهمتش. واش تقدر تعاود من فضلك؟', ar: 'آسف، لم أفهم. هل يمكنك أن تكرر من فضلك؟', fr: 'Désolé, je ne comprends pas. Vous pouvez répéter ?', en: "Sorry, I don't understand. Can you repeat, please?" },
            audio: 'en-US',
          },
        ],
        vocab: [
          { word: 'can I help you', audio: 'en-US', translation: { darija: 'واش نقدر نعاونك', ar: 'هل يمكنني مساعدتك', fr: 'puis-je vous aider', en: 'can I help you' } },
          { word: 'please', audio: 'en-US', translation: { darija: 'من فضلك', ar: 'من فضلك', fr: 's’il vous plaît', en: 'please' } },
          { word: 'how much', audio: 'en-US', translation: { darija: 'بشحال (ثمن)', ar: 'بكم', fr: 'combien (prix)', en: 'how much' } },
          { word: 'how many', audio: 'en-US', translation: { darija: 'شحال (عدد)', ar: 'كم عدد', fr: 'combien (nombre)', en: 'how many' } },
          { word: 'the bill', audio: 'en-US', translation: { darija: 'الحساب', ar: 'الفاتورة', fr: 'l’addition', en: 'the bill' } },
          { word: 'sorry', audio: 'en-US', translation: { darija: 'سمح لي', ar: 'آسف', fr: 'désolé', en: 'sorry' } },
          { word: 'understand', audio: 'en-US', translation: { darija: 'يفهم', ar: 'يفهم', fr: 'comprendre', en: 'to understand' } },
        ],
        exercises: [
          {
            id: 'en-a1-3-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: '___ is this jacket?', fr: '___ is this jacket?', en: 'How much is this jacket?' },
            options: [
              { text: 'How many' },
              { text: 'How much' },
              { text: 'What' },
              { text: 'Where' },
            ],
            answer: 1,
            explanation: { darija: 'How much = الثمن. How many = العدد.', fr: 'How much = le prix. How many = le nombre.', en: 'How much asks for a price, how many for a count.' },
          },
          {
            id: 'en-a1-3-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'Could you help me, ___?', fr: 'Could you help me, ___?', en: 'Could you help me, please?' },
            answer: 'please',
            accept: ['please'],
            explanation: { darija: 'please كتخلّي الطلب مهذب.', fr: '« please » rend la demande polie.', en: '"please" makes the request polite.' },
          },
          {
            id: 'en-a1-3-e3',
            type: 'translate',
            xp: 10,
            prompt: { en: 'The bill, please.', fr: 'L’addition, s’il vous plaît.' },
            answer: 'the bill please',
            accept: ['the bill please', 'bill please', 'could i have the bill please', 'the check please'],
            explanation: { darija: 'فـ أمريكا: the check. فـ بريطانيا: the bill.', fr: 'the check (US) / the bill (UK).', en: '"the check" in American English, "the bill" in British.' },
          },
          {
            id: 'en-a1-3-e4',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'A shop assistant says "Can I help you?" — you want to buy. You say:', fr: 'Une vendeuse dit « Can I help you? » — tu veux acheter. Tu réponds :', en: 'A shop assistant says "Can I help you?" — you want to buy. You say:' },
            options: [
              { text: 'No, I am fine.' },
              { text: 'Yes, please. I’d like this one, please.' },
              { text: 'Where is the toilet?' },
              { text: 'How much is it?' },
            ],
            answer: 1,
            explanation: { darija: '«I’d like this one, please» = بغيت هادي من فضلك.', fr: '« I’d like this one, please » = je voudrais celui-ci.', en: '"I’d like this one, please" is the natural reply.' },
          },
        ],
      },
    ],
  },
]
