export const spanishLessons = [
  {
    level: 'A1',
    lessons: [
      {
        id: 'es-a1-1',
        order: 1,
        icon: '\u{1F44B}',
        xp: 50,
        duration: 8,
        title: {
          native: 'Me llamo... y soy de...',
          darija: 'سمّيتي... و أنا من...',
          ar: 'اسمي... وأنا من...',
          fr: 'Je m’appelle… et je viens de…',
          en: 'My name is... and I am from...',
        },
        subtitle: {
          darija: 'الضمائر و ser / estar',
          ar: 'الضمائر وأفعال ser و estar',
          fr: 'Pronoms et ser / estar',
          en: 'Pronouns and ser / estar',
        },
        intro: {
          darija: 'الإسبانية قريبة من البرتغالية ومن الإيطالية. فيها جوج فعل: **ser** (الذات) و **estar** (الحالة والمكان).',
          ar: 'في الإسبانية فعلان: ser للهوية و estar للحالة والمكان.',
          fr: 'L’espagnol est proche du portugais. Deux verbes : ser (identité) et estar (état, lieu).',
        },
        sections: [
          {
            type: 'text',
            body: {
              es: '**ser** = identité, origine, profession.\nyo **soy**, tú **eres**, él/ella **es**, nosotros **somos**, vosotros **sois**, ellos/ellas **son**.\n\n**estar** = lieu, état, humeur.\nyo **estoy**, tú **estás**, él/ella **está**, nosotros **estamos**, vosotros **estáis**, ellos/ellas **están**.\n\n*Soy de Marruecos* = I am from Morocco. *Estoy en casa* = I am at home.',
              darija: '**ser** = الهوية، الجنسية، المهنة. **estar** = المكان والحالة.\n\n**Estoy en casa** = راني فـ الدار. **Soy de Marruecos** = مغربي، من المغرب.',
              ar: 'ser للهوية و estar للحالة والمكان. Estoy en casa = أنا في البيت.',
              fr: 'ser = identité, estar = état et lieu. Je suis marocain. Je suis à la maison.',
            },
          },
          {
            type: 'text',
            body: {
              es: '**Pronouns drop the ending -o:**\nyo hablo → *hablo* · nosotros hablamos → *hablamos*\ntú comes → *comes* · vosotros coméis → *coméis*\n\n**g** turns into **j** before e / i: *juego* (game), *joven* (young).\n**z** turns into **c** before e / i: *cerveza* (beer).',
              darija: 'الضمائر كتحيد **-o** فـ الآخر: hablo، comes.\n\n**g** كتولي **j** قبل e ولا i: juego، joven.',
              ar: 'الضمائر تحذف التاء في آخر الفعل المضارع. g تصبح j قبل e أو i.',
              fr: 'Les pronoms suppriment le -o final. g devient j devant e ou i.',
            },
          },
        ],
        examples: [
          {
            source: 'Hola, me llamo Karim. Soy de Casablanca.',
            translation: { darija: 'السلام عليكم، سميتي كريم. من الدار البيضاء.', ar: 'مرحبًا، اسمي كريم. من الدار البيضاء.', fr: 'Salut, je m’appelle Karim. Je viens de Casablanca.', en: 'Hi, I am Karim. I am from Casablanca.' },
            audio: 'es-ES',
          },
          {
            source: 'Estoy en Barcelona, pero soy de Rabat.',
            translation: { darija: 'راني فـ برشلونة، ولكن أنا من الرباط.', ar: 'أنا في برشلونة، لكني من الرباط.', fr: 'Je suis à Barcelone, mais je viens de Rabat.', en: 'I am in Barcelona, but I am from Rabat.' },
            audio: 'es-ES',
          },
          {
            source: 'Ella es profesora y está contenta.',
            translation: { darija: 'هي أستاذة و هي فرحانة.', ar: 'هي أستاذة وهي سعيدة.', fr: 'Elle est professeur et elle est heureuse.', en: 'She is a teacher and she is happy.' },
            audio: 'es-ES',
          },
        ],
        vocab: [
          { word: 'me llamo', audio: 'es-ES', translation: { darija: 'سمّيتي', ar: 'اسمي', fr: 'je m’appelle', en: 'my name is' } },
          { word: 'soy', audio: 'es-ES', translation: { darija: 'أنا (سكون)', ar: 'أنا', fr: 'je suis', en: 'I am' } },
          { word: 'estoy', audio: 'es-ES', translation: { darija: 'أنا (حالة/مكان)', ar: 'أنا (حالة)', fr: 'je suis (état)', en: 'I am (state)' } },
          { word: 'de', audio: 'es-ES', translation: { darija: 'من', ar: 'من', fr: 'de', en: 'from' } },
          { word: 'en', audio: 'es-ES', translation: { darija: 'فـ', ar: 'في', fr: 'à / dans', en: 'in / at' } },
          { word: 'la casa', audio: 'es-ES', translation: { darija: 'البيت', ar: 'المنزل', fr: 'la maison', en: 'the house' } },
          { word: 'gracias', audio: 'es-ES', translation: { darija: 'شكراً', ar: 'شكرًا', fr: 'merci', en: 'thank you' } },
          { word: 'buenos días', audio: 'es-ES', translation: { darija: 'صباح الخير', ar: 'صباح الخير', fr: 'bonjour', en: 'good morning' } },
        ],
        exercises: [
          {
            id: 'es-a1-1-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'Yo ___ de Marruecos.', fr: 'Yo ___ de Marruecos.', en: 'I am from Morocco.' },
            options: [
              { text: 'estoy' },
              { text: 'soy' },
              { text: 'tiene' },
              { text: 'va' },
            ],
            answer: 1,
            explanation: { darija: 'الجنسية والأصل بـ **ser** : soy de Marruecos.', fr: 'L’origine s’emploie avec ser : soy de Marruecos.', en: 'Origin uses ser: "soy de Marruecos".' },
          },
          {
            id: 'es-a1-1-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'Yo ___ en casa.', fr: 'Yo ___ en casa.', en: 'I am at home.' },
            answer: 'estoy',
            accept: ['estoy', 'estoi'],
            explanation: { darija: 'المكان بـ **estar** : estoy en casa.', fr: 'Le lieu s’emploie avec estar.', en: 'Location uses estar: "estoy en casa".' },
          },
          {
            id: 'es-a1-1-e3',
            type: 'translate',
            xp: 10,
            prompt: { es: 'My name is Fatima.', en: 'My name is Fatima.' },
            answer: 'me llamo fatima',
            accept: ['me llamo fatima', 'me llamo fatima', 'llamo fatima', 'yo me llamo fatima'],
            explanation: { darija: '«Me llamo» = سمّيتي. بلا ما نقولو «mi nombre es».', fr: 'On dit « me llamo », pas « mi nombre es ».', en: 'Spanish uses "me llamo", not "my name is".' },
          },
          {
            id: 'es-a1-1-e4',
            type: 'mcq',
            xp: 10,
            prompt: { native: 'Nosotros ___ estudiantes.', fr: 'Nosotros ___ estudiantes.', en: 'We are students.' },
            options: [
              { text: 'somos' },
              { text: 'estamos' },
              { text: 'son' },
              { text: 'estás' },
            ],
            answer: 0,
            explanation: { darija: 'nosotros + ser = somos. nosotros + estar = estamos.', fr: 'nosotros + ser = somos ; + estar = estamos.', en: 'nosotros takes somos with ser and estamos with estar.' },
          },
          {
            id: 'es-a1-1-e5',
            type: 'listen',
            xp: 15,
            audio: 'es-ES',
            audioText: 'Estoy en el mercado.',
            prompt: { fr: 'Écoute. Où est-il ?', en: 'Listen. Where is he?' },
            options: [
              { text: 'À la maison' },
              { text: 'Au marché' },
              { text: 'À l’école' },
              { text: 'Au travail' },
            ],
            answer: 1,
            explanation: { darija: 'el mercado = السوق.', fr: 'el mercado = le marché.', en: '"el mercado" means market.' },
          },
          {
            id: 'es-a1-1-e6',
            type: 'speak',
            xp: 20,
            audio: 'es-ES',
            audioText: 'Hola, me llamo Karim y soy de Casablanca.',
            prompt: { fr: 'Dis : « Hola, me llamo Karim y soy de Casablanca. »', en: 'Say: "Hello, I am Karim and I am from Casablanca."' },
            explanation: { darija: 'انتبه للـ j و ll. fـ Catalunya كي.gcari llsos rrr.', fr: 'Attention au j et au ll (lSevilla).', en: 'Mind the j and the ll sounds (like in "ella").' },
          },
        ],
      },
      {
        id: 'es-a1-2',
        order: 2,
        icon: '\u{1F345}',
        xp: 50,
        duration: 9,
        title: {
          native: 'En el mercado',
          darija: 'فـ السوق',
          ar: 'في السوق',
          fr: 'Au marché',
          en: 'At the market',
        },
        subtitle: {
          darija: 'الأرقام، الألوان، و la cuenta',
          ar: 'الأرقام والألوان والحساب',
          fr: 'Nombres, couleurs et l’addition',
          en: 'Numbers, colours and the bill',
        },
        intro: {
          darija: 'فـ إسبانيا كاين **el mercado** ديال الصباح، و**la cafetería**. الأرقام هناك غير ساهلين: **treinta** (30)، **cuarenta** (40)، **cincuenta** (50).',
          ar: 'السوق في إسبانيا صباحاً، والأرقام سهلة: treinta، cuarenta، cincuenta.',
          fr: 'Le marché le matin, et les nombres sont faciles : treinta, cuarenta, cincuenta.',
        },
        sections: [
          {
            type: 'text',
            body: {
              es: '**Los números 0-20:** cero, uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez, once, doce, trece, catorce, quince, dieciséis, diecisiete, dieciocho, diecinueve, veinte.\n\n**20-50:** treinta, cuarenta, cincuenta.\n\n**Colores:** rojo, azul, verde, amarillo, blanco, negro, naranja, morado.\n\n**¿Cuánto cuesta?** = How much is it?\n**La cuenta, por favor** = The bill, please.',
              darija: '**الأرقام من 0 لـ 20:** cero، uno، dos…\n**من 20 لـ 50:** treinta، cuarenta، cincuenta.\n\n**الألوان:** rojo (أحمر)، azul (أزرق)، verde (أخضر)، amarillo (أصفر)، blanco (أبيض)، negro (أسود).\n\n**¿Cuánto cuesta?** = بشحال؟\n**La cuenta, por favor** = الحساب من فضلك.',
              ar: 'الأرقام والألوان في الإسبانية. ¿Cuánto cuesta؟ = بكم الثمن؟',
              fr: 'Les nombres, les couleurs, ¿Cuánto cuesta؟ = combien ?',
            },
          },
        ],
        examples: [
          {
            source: '¿Cuánto cuestan las naranjas?',
            translation: { darija: 'بشحال البرتقال؟', ar: 'كم ثمن البرتقال؟', fr: 'Combien coûtent les oranges ?', en: 'How much are the oranges?' },
            audio: 'es-ES',
          },
          {
            source: 'Para llevar, por favor.',
            translation: { darija: 'للأخذ معي من فضلك.', ar: 'للأخذ معي من فضلك.', fr: 'À emporter, s’il vous plaît.', en: 'To take away, please.' },
            audio: 'es-ES',
          },
        ],
        vocab: [
          { word: 'el mercado', audio: 'es-ES', translation: { darija: 'السوق', ar: 'السوق', fr: 'le marché', en: 'the market' } },
          { word: 'el pan', audio: 'es-ES', translation: { darija: 'الخبز', ar: 'الخبز', fr: 'le pain', en: 'bread' } },
          { word: 'la cuenta', audio: 'es-ES', translation: { darija: 'الحساب', ar: 'الفاتورة', fr: 'l’addition', en: 'the bill' } },
          { word: 'rojo', audio: 'es-ES', translation: { darija: 'أحمر', ar: 'أحمر', fr: 'rouge', en: 'red' } },
          { word: 'verde', audio: 'es-ES', translation: { darija: 'أخضر', ar: 'أخضر', fr: 'vert', en: 'green' } },
          { word: 'cuánto', audio: 'es-ES', translation: { darija: 'شحال', ar: 'كم', fr: 'combien', en: 'how much' } },
        ],
        exercises: [
          {
            id: 'es-a1-2-e1',
            type: 'mcq',
            xp: 10,
            prompt: { native: '___ cuesta el café?', fr: '___ cuesta el café?', en: 'How much is the coffee?' },
            options: [
              { text: 'Qué' },
              { text: 'Cuánto' },
              { text: 'Dónde' },
              { text: 'Quién' },
            ],
            answer: 1,
            explanation: { darija: 'السؤال على الثمن: cuánto، و على الشيء: qué.', fr: 'Pour le prix : cuánto. Pour la chose : qué.', en: 'cuánto = how much, qué = what.' },
          },
          {
            id: 'es-a1-2-e2',
            type: 'fill',
            xp: 10,
            prompt: { native: 'La cuenta, ___ favor.', fr: 'La cuenta, ___ favor.', en: 'The bill, please.' },
            answer: 'por',
            accept: ['por'],
            explanation: { darija: '«por favor» = من فضلك. فـ الم-português هي نفسها.', fr: '« por favor » = s’il vous plaît.', en: '"por favor" means please.' },
          },
          {
            id: 'es-a1-2-e3',
            type: 'listen',
            xp: 15,
            audio: 'es-ES',
            audioText: 'Son cinco euros con cincuenta.',
            prompt: { fr: 'Écoute. Combien ?', en: 'Listen. How much?' },
            options: [
              { text: '5,50 €' },
              { text: '15,50 €' },
              { text: '50,50 €' },
              { text: '55,00 €' },
            ],
            answer: 0,
            explanation: { darija: 'cinco con cincuenta = 5,50.', fr: 'cinco con cincuenta = 5,50.', en: '"cinco con cincuenta" means 5.50.' },
          },
        ],
      },
    ],
  },
]
